// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: ChildHost.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiHostTests_ChildrenProof_ChildHost
{
struct FChildHostUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FChildHostUetkxProps& O = static_cast<const FChildHostUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode ChildHost(FChildHostUetkxProps InProps = FChildHostUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiHostTests_ChildrenProof_ChildHost
#else
namespace RuitkUetkx_Source_RuiHostTests_ChildrenProof_ChildHost
{
static FRuitkNodeArray ChildHost_UetkxBody_82FA7DEF(FRuitkContext& Ctx, const FChildHostUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return { [&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.ChildHost", "ChildHost_1", "HOST-HEADER"), FRuitkKey()));
		Ch.Append(children);
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.ChildHost", "ChildHost_2", "HOST-FOOTER"), FRuitkKey()));
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray ChildHost_UetkxImpl(FRuitkContext& Ctx, const FChildHostUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return ChildHost_UetkxBody_82FA7DEF(Ctx, Props, children);
}
static const FName GChildHostUetkxId = Ruitk::RegisterComponentId((void*)&ChildHost_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiHostTests_ChildrenProof_ChildHost::ChildHost")));
static constexpr uint32 ChildHost_RUI_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode ChildHost(FChildHostUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&ChildHost_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GChildHostUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiHostTests_ChildrenProof_ChildHost::ChildHost")), []() { return ChildHost(); });

} // namespace RuitkUetkx_Source_RuiHostTests_ChildrenProof_ChildHost
#endif
