// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: LabScopeBadge.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge
{
struct FLabScopeBadgeUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FLabScopeBadgeUetkxProps& O = static_cast<const FLabScopeBadgeUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode LabScopeBadge(FLabScopeBadgeUetkxProps InProps = FLabScopeBadgeUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge
{
static FRuitkNodeArray LabScopeBadge_UetkxBody_BC1A283F(FRuitkContext& Ctx, const FLabScopeBadgeUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return { Ruitk::TextBlock(NSLOCTEXT("Uetkx.LabScopeBadge", "LabScopeBadge_1", "scope-proof"), FRuitkKey()) };
}
static FRuitkNodeArray LabScopeBadge_UetkxImpl(FRuitkContext& Ctx, const FLabScopeBadgeUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return LabScopeBadge_UetkxBody_BC1A283F(Ctx, Props, children);
}
static const FName GLabScopeBadgeUetkxId = Ruitk::RegisterComponentId((void*)&LabScopeBadge_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge::LabScopeBadge")));
static constexpr uint32 LabScopeBadge_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode LabScopeBadge(FLabScopeBadgeUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&LabScopeBadge_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GLabScopeBadgeUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge::LabScopeBadge")), []() { return LabScopeBadge(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge
#endif
