// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: LabScopeProof.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof
{
struct FLabScopeProofUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FLabScopeProofUetkxProps& O = static_cast<const FLabScopeProofUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode LabScopeProof(FLabScopeProofUetkxProps InProps = FLabScopeProofUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof
{
static FRuitkNodeArray LabScopeProof_UetkxBody_680F6C6D(FRuitkContext& Ctx, const FLabScopeProofUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return { [&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge::FLabScopeBadgeUetkxProps P;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge::LabScopeBadge(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderBackgroundColor((RuitkUetkx_Source_RuitkDemo_Screens_SimpleCounter_SimpleCounter_style::PanelBackground()));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(24.f, 6.f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderBackgroundColor((RuitkUetkx_Source_RuitkDemo_Screens_ContextDemo_ContextDemo_style::PanelBackground()));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(24.f, 6.f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray LabScopeProof_UetkxImpl(FRuitkContext& Ctx, const FLabScopeProofUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return LabScopeProof_UetkxBody_680F6C6D(Ctx, Props, children);
}
static const FName GLabScopeProofUetkxId = Ruitk::RegisterComponentId((void*)&LabScopeProof_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof::LabScopeProof")));
static constexpr uint32 LabScopeProof_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode LabScopeProof(FLabScopeProofUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&LabScopeProof_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GLabScopeProofUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof::LabScopeProof")), []() { return LabScopeProof(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof
#endif
