// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: CycleA.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleA
{
struct FCycleAUetkxProps final : public FRuitkPropsBase
{
	int32 Depth = 0;

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FCycleAUetkxProps& O = static_cast<const FCycleAUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (Depth == O.Depth);
		return bEq;
	}
};
inline FRuitkNode CycleA(FCycleAUetkxProps InProps = FCycleAUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleA
#else
namespace RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleA
{
static FRuitkNodeArray CycleA_UetkxBody_34BA9648(FRuitkContext& Ctx, const FCycleAUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	const auto& Depth = Props.Depth;
	return { [&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.CycleA", "CycleA_1", "A"), FRuitkKey()));
		if (Depth > 0)
		{
			Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleB::FCycleBUetkxProps P;
		P.Depth = Depth - 1;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleB::CycleB(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray CycleA_UetkxImpl(FRuitkContext& Ctx, const FCycleAUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return CycleA_UetkxBody_34BA9648(Ctx, Props, children);
}
static const FName GCycleAUetkxId = Ruitk::RegisterComponentId((void*)&CycleA_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleA::CycleA")));
static constexpr uint32 CycleA_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode CycleA(FCycleAUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&CycleA_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GCycleAUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleA::CycleA")), []() { return CycleA(); });

} // namespace RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleA
#endif
