// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: CycleB.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleB
{
struct FCycleBUetkxProps final : public FRuitkPropsBase
{
	int32 Depth = 0;

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FCycleBUetkxProps& O = static_cast<const FCycleBUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (Depth == O.Depth);
		return bEq;
	}
};
inline FRuitkNode CycleB(FCycleBUetkxProps InProps = FCycleBUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleB
#else
namespace RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleB
{
static FRuitkNodeArray CycleB_UetkxBody_E880605E(FRuitkContext& Ctx, const FCycleBUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	const auto& Depth = Props.Depth;
	return { [&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.CycleB", "CycleB_1", "B"), FRuitkKey()));
		if (Depth > 0)
		{
			Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleA::FCycleAUetkxProps P;
		P.Depth = Depth - 1;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleA::CycleA(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray CycleB_UetkxImpl(FRuitkContext& Ctx, const FCycleBUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return CycleB_UetkxBody_E880605E(Ctx, Props, children);
}
static const FName GCycleBUetkxId = Ruitk::RegisterComponentId((void*)&CycleB_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleB::CycleB")));
static constexpr uint32 CycleB_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode CycleB(FCycleBUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&CycleB_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GCycleBUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleB::CycleB")), []() { return CycleB(); });

} // namespace RuitkUetkx_Source_RuitkHostTests_CycleProof_CycleB
#endif
