// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: SimpleUseEffect.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_SimpleUseEffect_SimpleUseEffect
{
struct FSimpleUseEffectUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FSimpleUseEffectUetkxProps& O = static_cast<const FSimpleUseEffectUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode SimpleUseEffect(FSimpleUseEffectUetkxProps InProps = FSimpleUseEffectUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_SimpleUseEffect_SimpleUseEffect
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_SimpleUseEffect_SimpleUseEffect
{
static FRuitkNodeArray SimpleUseEffect_UetkxBody_2E73F0B0(FRuitkContext& Ctx, const FSimpleUseEffectUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 2 "Source/RuitkDemo/Screens/SimpleUseEffect/SimpleUseEffect.uetkx"
	auto [Message, SetMessage] = Ctx.UseState<FString>(FString(TEXT("Waiting...")));
		Ctx.UseEffect([SetMessage]() { SetMessage(FString(TEXT("Effect ran!"))); }, Ruitk::Deps());
#line 30 "SimpleUseEffect.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("Message: {}"), Message)), FRuitkKey()));
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray SimpleUseEffect_UetkxImpl(FRuitkContext& Ctx, const FSimpleUseEffectUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return SimpleUseEffect_UetkxBody_2E73F0B0(Ctx, Props, children);
}
static const FName GSimpleUseEffectUetkxId = Ruitk::RegisterComponentId((void*)&SimpleUseEffect_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_SimpleUseEffect_SimpleUseEffect::SimpleUseEffect")));
static constexpr uint32 SimpleUseEffect_RUITK_HOOK_SIG = 0x7B306E79u;
inline FRuitkNode SimpleUseEffect(FSimpleUseEffectUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&SimpleUseEffect_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GSimpleUseEffectUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_SimpleUseEffect_SimpleUseEffect::SimpleUseEffect")), []() { return SimpleUseEffect(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_SimpleUseEffect_SimpleUseEffect
#endif
