// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: LabCard.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard
{
struct FLabCardUetkxProps final : public FRuitkPropsBase
{
	FString Label = FString(TEXT("Card"));
	int32 Count = 0;

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FLabCardUetkxProps& O = static_cast<const FLabCardUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (Label == O.Label);
		bEq = bEq && (Count == O.Count);
		return bEq;
	}
};
inline FRuitkNode LabCard(FLabCardUetkxProps InProps = FLabCardUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard
{
static FRuitkNodeArray LabCard_UetkxBody_0A2A00D8(FRuitkContext& Ctx, const FLabCardUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	const auto& Label = Props.Label;
	const auto& Count = Props.Count;
#line 18 "Source/RuitkDemo/Screens/AcceptanceLab/components/LabCard/LabCard.uetkx"
	// Simple derived value from a prop — exercises reading component props in the setup block.
		const FLinearColor Tint = Count > 0 ? RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Good() : RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Warn();
#line 36 "LabCard.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.05f, 0.05f, 0.07f, 0.9f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((FText::FromString(Label)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(12.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Accent()));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("value = {}"), Count)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Tint));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray LabCard_UetkxImpl(FRuitkContext& Ctx, const FLabCardUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return LabCard_UetkxBody_0A2A00D8(Ctx, Props, children);
}
static const FName GLabCardUetkxId = Ruitk::RegisterComponentId((void*)&LabCard_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard::LabCard")));
static constexpr uint32 LabCard_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode LabCard(FLabCardUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&LabCard_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GLabCardUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard::LabCard")), []() { return LabCard(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard
#endif
