// AUTO-GENERATED by RUICompile — DO NOT EDIT. Source: LabScopeBadge.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUI_UETKX_DECL_PHASE)
namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge
{
struct FLabScopeBadgeUetkxProps final : public FRuiPropsBase
{

	virtual bool Equals(const FRuiPropsBase& OtherBase) const override
	{
		const FLabScopeBadgeUetkxProps& O = static_cast<const FLabScopeBadgeUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuiNode LabScopeBadge(FLabScopeBadgeUetkxProps InProps = FLabScopeBadgeUetkxProps(), TArray<FRuiNode> InChildren = TArray<FRuiNode>(), FRuiKey InKey = FRuiKey());

} // namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge
#else
namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge
{
static FRuiNodeArray LabScopeBadge_UetkxImpl_BC1A283F(FRuiContext& Ctx, const FLabScopeBadgeUetkxProps& Props, const TArray<FRuiNode>& children)
{
	return { RUI::TextBlock(NSLOCTEXT("Uetkx.LabScopeBadge", "LabScopeBadge_1", "scope-proof"), FRuiKey()) };
}
static const FName GLabScopeBadgeUetkxId = RUI::RegisterComponentId((void*)&LabScopeBadge_UetkxImpl_BC1A283F, FName(TEXT("RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge::LabScopeBadge")));
static constexpr uint32 LabScopeBadge_RUI_HOOK_SIG = 0x811C9DC5u;
inline FRuiNode LabScopeBadge(FLabScopeBadgeUetkxProps InProps, TArray<FRuiNode> InChildren, FRuiKey InKey)
{
	return RUI::FC(&LabScopeBadge_UetkxImpl_BC1A283F, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GLabScopeBadgeUetkxFactoryReg = RUI::RegisterNamedFactory(FName(TEXT("RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge::LabScopeBadge")), []() { return LabScopeBadge(); });

} // namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge
#endif
