// AUTO-GENERATED by RUICompile — DO NOT EDIT. Source: LabScopeProof.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUI_UETKX_DECL_PHASE)
namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof
{
struct FLabScopeProofUetkxProps final : public FRuiPropsBase
{

	virtual bool Equals(const FRuiPropsBase& OtherBase) const override
	{
		const FLabScopeProofUetkxProps& O = static_cast<const FLabScopeProofUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuiNode LabScopeProof(FLabScopeProofUetkxProps InProps = FLabScopeProofUetkxProps(), TArray<FRuiNode> InChildren = TArray<FRuiNode>(), FRuiKey InKey = FRuiKey());

} // namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof
#else
namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof
{
static FRuiNodeArray LabScopeProof_UetkxImpl_62E89A38(FRuiContext& Ctx, const FLabScopeProofUetkxProps& Props, const TArray<FRuiNode>& children)
{
	return { [&]() -> FRuiNode {
		FRuiVerticalBoxProps P;
		TArray<FRuiNode> Ch;
		Ch.Add([&]() -> FRuiNode {
		RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge::FLabScopeBadgeUetkxProps P;
		TArray<FRuiNode> Ch;
		return RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeBadge::LabScopeBadge(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}());
		Ch.Add([&]() -> FRuiNode {
		FRuiBorderProps P;
		P.SetBorderBackgroundColor((RuiUetkx_Source_RuiDemo_Screens_SimpleCounter_SimpleCounter_style::PanelBackground()));
		TSharedRef<FRuiStyleDict> __Style = MakeShared<FRuiStyleDict>();
		TSharedRef<FRuiStyleDict> __Slot = MakeShared<FRuiStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuiValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuiNode> Ch;
		Ch.Add([&]() -> FRuiNode {
		FRuiSpacerProps P;
		P.SetSize((FVector2D(24.f, 6.f)));
		return RUI::Slate::Spacer(MoveTemp(P), FRuiKey());
	}());
		return RUI::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}());
		Ch.Add([&]() -> FRuiNode {
		FRuiBorderProps P;
		P.SetBorderBackgroundColor((RuiUetkx_Source_RuiDemo_Screens_ContextDemo_ContextDemo_style::PanelBackground()));
		TSharedRef<FRuiStyleDict> __Style = MakeShared<FRuiStyleDict>();
		TSharedRef<FRuiStyleDict> __Slot = MakeShared<FRuiStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuiValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuiNode> Ch;
		Ch.Add([&]() -> FRuiNode {
		FRuiSpacerProps P;
		P.SetSize((FVector2D(24.f, 6.f)));
		return RUI::Slate::Spacer(MoveTemp(P), FRuiKey());
	}());
		return RUI::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}());
		return RUI::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}() };
}
static const FName GLabScopeProofUetkxId = RUI::RegisterComponentId((void*)&LabScopeProof_UetkxImpl_62E89A38, FName(TEXT("RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof::LabScopeProof")));
static constexpr uint32 LabScopeProof_RUI_HOOK_SIG = 0x811C9DC5u;
inline FRuiNode LabScopeProof(FLabScopeProofUetkxProps InProps, TArray<FRuiNode> InChildren, FRuiKey InKey)
{
	return RUI::FC(&LabScopeProof_UetkxImpl_62E89A38, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GLabScopeProofUetkxFactoryReg = RUI::RegisterNamedFactory(FName(TEXT("RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof::LabScopeProof")), []() { return LabScopeProof(); });

} // namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof
#endif
