// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: SimpleCounter.style.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_SimpleCounter_SimpleCounter_style
{
inline FLinearColor PanelBackground()
{
	return
#line 8 "Source/RuitkDemo/Screens/SimpleCounter/SimpleCounter.style.uetkx"
{ 0.02f, 0.02f, 0.03f, 0.85f }
#line 14 "SimpleCounter.style.uetkx.inl"
;
}

inline FMargin PanelPadding()
{
	return
#line 10 "Source/RuitkDemo/Screens/SimpleCounter/SimpleCounter.style.uetkx"
{ 12.0f }
#line 23 "SimpleCounter.style.uetkx.inl"
;
}

inline FMargin ButtonPadding()
{
	return
#line 12 "Source/RuitkDemo/Screens/SimpleCounter/SimpleCounter.style.uetkx"
{ 12.0f, 4.0f }
#line 32 "SimpleCounter.style.uetkx.inl"
;
}

inline FVector2D RowGap()
{
	return
#line 14 "Source/RuitkDemo/Screens/SimpleCounter/SimpleCounter.style.uetkx"
{ 1.0f, 6.0f }
#line 41 "SimpleCounter.style.uetkx.inl"
;
}

inline FString PanelSlotPadding()
{
	return
#line 16 "Source/RuitkDemo/Screens/SimpleCounter/SimpleCounter.style.uetkx"
TEXT("0,10,0,0")
#line 50 "SimpleCounter.style.uetkx.inl"
;
}

inline FString ButtonSlotPadding()
{
	return
#line 18 "Source/RuitkDemo/Screens/SimpleCounter/SimpleCounter.style.uetkx"
TEXT("0,0,6,0")
#line 59 "SimpleCounter.style.uetkx.inl"
;
}

} // namespace RuitkUetkx_Source_RuiDemo_Screens_SimpleCounter_SimpleCounter_style
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_SimpleCounter_SimpleCounter_style
{
} // namespace RuitkUetkx_Source_RuiDemo_Screens_SimpleCounter_SimpleCounter_style
#endif
