// AUTO-GENERATED by RUICompile — DO NOT EDIT. Source: HelloWorld.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUI_UETKX_DECL_PHASE)
namespace RuiUetkx_Source_RuiDemo_Screens_HelloWorld_HelloWorld
{
struct FHelloWorldUetkxProps final : public FRuiPropsBase
{

	virtual bool Equals(const FRuiPropsBase& OtherBase) const override
	{
		const FHelloWorldUetkxProps& O = static_cast<const FHelloWorldUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuiNode HelloWorld(FHelloWorldUetkxProps InProps = FHelloWorldUetkxProps(), TArray<FRuiNode> InChildren = TArray<FRuiNode>(), FRuiKey InKey = FRuiKey());

} // namespace RuiUetkx_Source_RuiDemo_Screens_HelloWorld_HelloWorld
#else
namespace RuiUetkx_Source_RuiDemo_Screens_HelloWorld_HelloWorld
{
static FRuiNodeArray HelloWorld_UetkxImpl_6146BE1F(FRuiContext& Ctx, const FHelloWorldUetkxProps& Props, const TArray<FRuiNode>& children)
{
	return { [&]() -> FRuiNode {
		FRuiBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuiStyleDict> __Style = MakeShared<FRuiStyleDict>();
		TSharedRef<FRuiStyleDict> __Slot = MakeShared<FRuiStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuiValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuiNode> Ch;
		Ch.Add(RUI::TextBlock(NSLOCTEXT("Uetkx.HelloWorld", "HelloWorld_1", "Hello, world! (compiled from HelloWorld.uetkx)"), FRuiKey()));
		return RUI::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}() };
}
static const FName GHelloWorldUetkxId = RUI::RegisterComponentId((void*)&HelloWorld_UetkxImpl_6146BE1F, FName(TEXT("RuiUetkx_Source_RuiDemo_Screens_HelloWorld_HelloWorld::HelloWorld")));
static constexpr uint32 HelloWorld_RUI_HOOK_SIG = 0x811C9DC5u;
inline FRuiNode HelloWorld(FHelloWorldUetkxProps InProps, TArray<FRuiNode> InChildren, FRuiKey InKey)
{
	return RUI::FC(&HelloWorld_UetkxImpl_6146BE1F, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GHelloWorldUetkxFactoryReg = RUI::RegisterNamedFactory(FName(TEXT("RuiUetkx_Source_RuiDemo_Screens_HelloWorld_HelloWorld::HelloWorld")), []() { return HelloWorld(); });

} // namespace RuiUetkx_Source_RuiDemo_Screens_HelloWorld_HelloWorld
#endif
