// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: InteropShowcase.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "RuitkDemoSupport.h"
#include "DemoUmgWidget.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_InteropShowcase_InteropShowcase
{
struct FInteropShowcaseUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FInteropShowcaseUetkxProps& O = static_cast<const FInteropShowcaseUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode InteropShowcase(FInteropShowcaseUetkxProps InProps = FInteropShowcaseUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_InteropShowcase_InteropShowcase
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_InteropShowcase_InteropShowcase
{
static FRuitkNodeArray InteropShowcase_UetkxBody_8217024D(FRuitkContext& Ctx, const FInteropShowcaseUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 9 "Source/RuitkDemo/Screens/InteropShowcase/InteropShowcase.uetkx"
	// MVVM pillar — a viewmodel we own; UseField re-renders on its broadcast.
		const TStrongObjectPtr<URuitkSignalViewModel>& VmPtr = Ctx.UseMemo<TStrongObjectPtr<URuitkSignalViewModel>>(
			[]() { return TStrongObjectPtr<URuitkSignalViewModel>(NewObject<URuitkSignalViewModel>()); }, Ruitk::Deps());
		URuitkSignalViewModel* Vm = VmPtr.Get();
		const int32 N = Ruitk::Umg::UseField<int32>(Ctx, Vm, FName(TEXT("Int")), 0);
	
		// CommonUI pillar — provide activation state to the probe below (a toggle stands in for a stack
		// push here; the CommonUI screen demos the real stack). The demo world comes from the game mode.
		UWorld* World = RuitkDemo::GetDemoWorld();
		auto [bActive, SetActive] = Ctx.UseState<bool>(true);
		FRuitkActivationState State;
		State.bActive = bActive;
		State.InputMethod = ERuitkInputMethod::MouseAndKeyboard;
		Ctx.ProvideContext(Ruitk::CommonUI::ActivationContext(), State);
#line 44 "InteropShowcase.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.InteropShowcase", "InteropShowcase_1", "All four pillars in one screen"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(18.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.InteropShowcase", "InteropShowcase_2", "Slate output - a UMG widget hosted inside - MVVM data feeding in - CommonUI activation"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 12.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.InteropShowcase", "InteropShowcase_3", "UMG -- their widget inside ours:"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add((World ? Ruitk::Umg::UserWidget(UDemoUmgWidget::StaticClass(), World) : Ruitk::TextBlock(FString(TEXT("[press Play -- the UMG host needs a running world]")))));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 12.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.InteropShowcase", "InteropShowcase_4", "MVVM -- their data inside ours:"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("viewmodel.Int = {}"), N)), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { Vm->SetInt(N + 1); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,0,10")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.InteropShowcase", "InteropShowcase_5", "viewmodel.SetInt(+1)")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.InteropShowcase", "InteropShowcase_6", "CommonUI -- their activation driving ours:"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuiDemo_Screens_InteropShowcase_components_ShowcaseProbe_ShowcaseProbe::FShowcaseProbeUetkxProps P;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuiDemo_Screens_InteropShowcase_components_ShowcaseProbe_ShowcaseProbe::ShowcaseProbe(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetActive(!bActive); }));
		P.SetContentPadding(FMargin(12,4));
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.InteropShowcase", "InteropShowcase_7", "Toggle activation")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray InteropShowcase_UetkxImpl(FRuitkContext& Ctx, const FInteropShowcaseUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return InteropShowcase_UetkxBody_8217024D(Ctx, Props, children);
}
static const FName GInteropShowcaseUetkxId = Ruitk::RegisterComponentId((void*)&InteropShowcase_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_InteropShowcase_InteropShowcase::InteropShowcase")));
static constexpr uint32 InteropShowcase_RUITK_HOOK_SIG = 0x4EA045DDu;
inline FRuitkNode InteropShowcase(FInteropShowcaseUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&InteropShowcase_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GInteropShowcaseUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_InteropShowcase_InteropShowcase::InteropShowcase")), []() { return InteropShowcase(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_InteropShowcase_InteropShowcase
#endif
