// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: SignalPanel.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "RuitkDemoSupport.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_SignalCounter_components_SignalPanel_SignalPanel
{
struct FSignalPanelUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FSignalPanelUetkxProps& O = static_cast<const FSignalPanelUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode SignalPanel(FSignalPanelUetkxProps InProps = FSignalPanelUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_SignalCounter_components_SignalPanel_SignalPanel
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_SignalCounter_components_SignalPanel_SignalPanel
{
static FRuitkNodeArray SignalPanel_UetkxBody_BF98A1C7(FRuitkContext& Ctx, const FSignalPanelUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 4 "Source/RuitkDemo/Screens/SignalCounter/components/SignalPanel/SignalPanel.uetkx"
	const int32 Count = Ruitk::UseSignalKey<int32>(Ctx, RuitkDemo::GDemoCounterSignal, 0);
#line 30 "SignalPanel.uetkx.inl"
	return { Ruitk::TextBlock((Ruitk::Fmt(TEXT("Count: {}"), Count)), FRuitkKey()) };
}
static FRuitkNodeArray SignalPanel_UetkxImpl(FRuitkContext& Ctx, const FSignalPanelUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return SignalPanel_UetkxBody_BF98A1C7(Ctx, Props, children);
}
static const FName GSignalPanelUetkxId = Ruitk::RegisterComponentId((void*)&SignalPanel_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_SignalCounter_components_SignalPanel_SignalPanel::SignalPanel")));
static constexpr uint32 SignalPanel_RUITK_HOOK_SIG = 0xD50F149Cu;
inline FRuitkNode SignalPanel(FSignalPanelUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&SignalPanel_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GSignalPanelUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_SignalCounter_components_SignalPanel_SignalPanel::SignalPanel")), []() { return SignalPanel(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_SignalCounter_components_SignalPanel_SignalPanel
#endif
