// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: SimpleTextField.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_SimpleTextField_SimpleTextField
{
struct FSimpleTextFieldUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FSimpleTextFieldUetkxProps& O = static_cast<const FSimpleTextFieldUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode SimpleTextField(FSimpleTextFieldUetkxProps InProps = FSimpleTextFieldUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_SimpleTextField_SimpleTextField
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_SimpleTextField_SimpleTextField
{
static FRuitkNodeArray SimpleTextField_UetkxBody_337F2464(FRuitkContext& Ctx, const FSimpleTextFieldUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 2 "Source/RuitkDemo/Screens/SimpleTextField/SimpleTextField.uetkx"
	auto [Text, SetText] = Ctx.UseState<FString>(FString());
#line 29 "SimpleTextField.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkEditableTextBoxProps P;
		P.SetText((FText::FromString(Text)));
		P.SetHintText(NSLOCTEXT("Uetkx.SimpleTextField", "SimpleTextField_1", "Type here..."));
		P.SetOnTextChanged(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetText(Value.TextValue.ToString()); }));
		return Ruitk::Slate::EditableTextBox(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("You typed: {}"), Text)), FRuitkKey()));
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray SimpleTextField_UetkxImpl(FRuitkContext& Ctx, const FSimpleTextFieldUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return SimpleTextField_UetkxBody_337F2464(Ctx, Props, children);
}
static const FName GSimpleTextFieldUetkxId = Ruitk::RegisterComponentId((void*)&SimpleTextField_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_SimpleTextField_SimpleTextField::SimpleTextField")));
static constexpr uint32 SimpleTextField_RUITK_HOOK_SIG = 0x986DF5F6u;
inline FRuitkNode SimpleTextField(FSimpleTextFieldUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&SimpleTextField_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GSimpleTextFieldUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_SimpleTextField_SimpleTextField::SimpleTextField")), []() { return SimpleTextField(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_SimpleTextField_SimpleTextField
#endif
