// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: UmgHostInner.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_components_UmgHostInner_UmgHostInner
{
struct FUmgHostInnerUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FUmgHostInnerUetkxProps& O = static_cast<const FUmgHostInnerUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode UmgHostInner(FUmgHostInnerUetkxProps InProps = FUmgHostInnerUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_components_UmgHostInner_UmgHostInner
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_components_UmgHostInner_UmgHostInner
{
static FRuitkNodeArray UmgHostInner_UetkxBody_494743D1(FRuitkContext& Ctx, const FUmgHostInnerUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 4 "Source/RuitkDemo/Screens/UmgHostDemo/components/UmgHostInner/UmgHostInner.uetkx"
	auto [Count, SetCount] = Ctx.UseState<int32>(0);
#line 29 "UmgHostInner.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.08f, 0.22f, 0.14f, 0.95f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.UmgHostInner", "UmgHostInner_1", "▼ Reactive UI Toolkit again — mounted INSIDE that UMG widget by URuitkHostWidget"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.6f, 1.0f, 0.7f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetCount(Count + 1); }));
		P.SetContentPadding(FMargin(10,3));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,4,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.UmgHostInner", "UmgHostInner_2", "+1")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT(" hooks work in here: {}"), Count)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,7,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray UmgHostInner_UetkxImpl(FRuitkContext& Ctx, const FUmgHostInnerUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return UmgHostInner_UetkxBody_494743D1(Ctx, Props, children);
}
static const FName GUmgHostInnerUetkxId = Ruitk::RegisterComponentId((void*)&UmgHostInner_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_components_UmgHostInner_UmgHostInner::UmgHostInner")));
static constexpr uint32 UmgHostInner_RUITK_HOOK_SIG = 0x986DF5F6u;
inline FRuitkNode UmgHostInner(FUmgHostInnerUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&UmgHostInner_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GUmgHostInnerUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_components_UmgHostInner_UmgHostInner::UmgHostInner")), []() { return UmgHostInner(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_components_UmgHostInner_UmgHostInner
#endif
