// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: DoomMainMenu.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "Doom/DoomMaps.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMainMenu_DoomMainMenu
{
struct FDoomMainMenuUetkxProps final : public FRuitkPropsBase
{
	int32 Level = 1;
	int32 Diff = 1;
	FRuitkCallback OnLevelChange = FRuitkCallback();
	FRuitkCallback OnDifficultyChange = FRuitkCallback();
	FRuitkCallback OnStart = FRuitkCallback();

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FDoomMainMenuUetkxProps& O = static_cast<const FDoomMainMenuUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (Level == O.Level);
		bEq = bEq && (Diff == O.Diff);
		bEq = bEq && (OnLevelChange == O.OnLevelChange);
		bEq = bEq && (OnDifficultyChange == O.OnDifficultyChange);
		bEq = bEq && (OnStart == O.OnStart);
		return bEq;
	}
};
inline FRuitkNode DoomMainMenu(FDoomMainMenuUetkxProps InProps = FDoomMainMenuUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMainMenu_DoomMainMenu
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMainMenu_DoomMainMenu
{
static FRuitkNodeArray DoomMainMenu_UetkxBody_F6778A6A(FRuitkContext& Ctx, const FDoomMainMenuUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	const auto& Level = Props.Level;
	const auto& Diff = Props.Diff;
	const auto& OnLevelChange = Props.OnLevelChange;
	const auto& OnDifficultyChange = Props.OnDifficultyChange;
	const auto& OnStart = Props.OnStart;
#line 9 "Source/RuitkDemo/Screens/DoomDemo/components/DoomMainMenu/DoomMainMenu.uetkx"
	const FLinearColor Bg(0.06f, 0.05f, 0.05f, 1.0f);
		const FLinearColor TitleClr(0.95f, 0.20f, 0.15f, 1.0f);
		const FLinearColor SubtitleClr(0.85f, 0.70f, 0.40f, 1.0f);
		const FLinearColor LabelClr(0.95f, 0.85f, 0.50f, 1.0f);
		const FLinearColor BtnFace(0.18f, 0.05f, 0.05f, 1.0f);
		const FLinearColor BtnText(0.95f, 0.95f, 0.85f, 1.0f);
		const FLinearColor BtnBorder(0.85f, 0.40f, 0.20f, 1.0f);
		const FLinearColor BtnSelected(0.40f, 0.10f, 0.05f, 1.0f);
		const FLinearColor HintClr(0.60f, 0.50f, 0.30f, 1.0f);
	
		static const TCHAR* DiffLabels[] = {TEXT("I'm too young to die"), TEXT("Hurt me plenty"), TEXT("Ultra-violence")};
#line 55 "DoomMainMenu.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((Bg));
		P.SetHAlign(FName(TEXT("center")));
		P.SetVAlign(FName(TEXT("center")));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomMainMenu", "DoomMainMenu_1", "DOOM"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(96.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(TitleClr));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,0,4")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomMainMenu", "DoomMainMenu_2", "(in .uetkx)"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(18.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(SubtitleClr));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,0,30")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,0,28")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomMainMenu", "DoomMainMenu_3", "EPISODE 1   —"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(LabelClr));
		__Slot->Add(FName(TEXT("Slot.VAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,12,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		for (int32 i = 1; i <= RuitkDoom::LEVEL_COUNT; ++i)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((Level == i ? BtnSelected : BtnBorder));
		P.SetPadding(FMargin(2));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.VAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("4,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((Level == i ? BtnSelected : BtnFace));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { OnLevelChange.Execute(FRuitkValue(i)); }));
		P.SetContentPadding(FMargin(14,6));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((FText::FromString(RuitkDoom::LevelName(i))), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(13.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(BtnText));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(*FString::Printf(TEXT("lv%d"), i))));
	}());
		}
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,0,36")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomMainMenu", "DoomMainMenu_4", "DIFFICULTY  —"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(LabelClr));
		__Slot->Add(FName(TEXT("Slot.VAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,12,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		for (int32 d = 0; d < 3; ++d)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((Diff == d ? BtnSelected : BtnBorder));
		P.SetPadding(FMargin(2));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.VAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("4,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((Diff == d ? BtnSelected : BtnFace));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { OnDifficultyChange.Execute(FRuitkValue(d)); }));
		P.SetContentPadding(FMargin(14,6));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((FText::FromString(DiffLabels[d])), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(13.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(BtnText));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(*FString::Printf(TEXT("df%d"), d))));
	}());
		}
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((BtnBorder));
		P.SetPadding(FMargin(3));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.5f, 0.1f, 0.05f, 1.0f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((280.0f));
		P.SetHeightOverride((60.0f));
		P.SetHAlign(FName(TEXT("center")));
		P.SetVAlign(FName(TEXT("center")));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { OnStart.Execute(); }));
		P.SetContentPadding(FMargin(14,8));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomMainMenu", "DoomMainMenu_5", "▶  START GAME"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(22.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(BtnText));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomMainMenu", "DoomMainMenu_6", "WASD = move    |    Mouse = look    |    Click = shoot    |    1-7 = weapons    |    E = use door    |    Shift = run"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(12.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(HintClr));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,36,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray DoomMainMenu_UetkxImpl(FRuitkContext& Ctx, const FDoomMainMenuUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return DoomMainMenu_UetkxBody_F6778A6A(Ctx, Props, children);
}
static const FName GDoomMainMenuUetkxId = Ruitk::RegisterComponentId((void*)&DoomMainMenu_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMainMenu_DoomMainMenu::DoomMainMenu")));
static constexpr uint32 DoomMainMenu_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode DoomMainMenu(FDoomMainMenuUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&DoomMainMenu_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GDoomMainMenuUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMainMenu_DoomMainMenu::DoomMainMenu")), []() { return DoomMainMenu(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMainMenu_DoomMainMenu
#endif
