// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: RouterUser.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterUser_RouterUser
{
struct FRouterUserUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FRouterUserUetkxProps& O = static_cast<const FRouterUserUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode RouterUser(FRouterUserUetkxProps InProps = FRouterUserUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterUser_RouterUser
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterUser_RouterUser
{
static FRuitkNodeArray RouterUser_UetkxBody_84C60909(FRuitkContext& Ctx, const FRouterUserUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 3 "Source/RuitkDemo/Screens/RouterDemo/components/RouterUser/RouterUser.uetkx"
	const TMap<FString, FString>& Params = UseParams(Ctx);
		auto Navigate = UseNavigate(Ctx);
#line 30 "RouterUser.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("User {}"), Params[TEXT("id")])), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { Navigate(TEXT("/"), false); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,6,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.RouterUser", "RouterUser_1", "Back home")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray RouterUser_UetkxImpl(FRuitkContext& Ctx, const FRouterUserUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return RouterUser_UetkxBody_84C60909(Ctx, Props, children);
}
static const FName GRouterUserUetkxId = Ruitk::RegisterComponentId((void*)&RouterUser_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterUser_RouterUser::RouterUser")));
static constexpr uint32 RouterUser_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode RouterUser(FRouterUserUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&RouterUser_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GRouterUserUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterUser_RouterUser::RouterUser")), []() { return RouterUser(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterUser_RouterUser
#endif
