// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: RouterHome.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterHome_RouterHome
{
struct FRouterHomeUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FRouterHomeUetkxProps& O = static_cast<const FRouterHomeUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode RouterHome(FRouterHomeUetkxProps InProps = FRouterHomeUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterHome_RouterHome
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterHome_RouterHome
{
static FRuitkNodeArray RouterHome_UetkxBody_85C2C783(FRuitkContext& Ctx, const FRouterHomeUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 3 "Source/RuitkDemo/Screens/RouterDemo/components/RouterHome/RouterHome.uetkx"
	auto Navigate = UseNavigate(Ctx);
		const FString Path = UsePathname(Ctx);
#line 30 "RouterHome.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("Location: {}"), Path)), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.RouterHome", "RouterHome_1", "Home — pick a user:"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { Navigate(TEXT("/users/42"), false); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,6,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.RouterHome", "RouterHome_2", "Open user 42")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { Navigate(TEXT("/users/7"), false); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,4,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.RouterHome", "RouterHome_3", "Open user 7")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray RouterHome_UetkxImpl(FRuitkContext& Ctx, const FRouterHomeUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return RouterHome_UetkxBody_85C2C783(Ctx, Props, children);
}
static const FName GRouterHomeUetkxId = Ruitk::RegisterComponentId((void*)&RouterHome_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterHome_RouterHome::RouterHome")));
static constexpr uint32 RouterHome_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode RouterHome(FRouterHomeUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&RouterHome_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GRouterHomeUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterHome_RouterHome::RouterHome")), []() { return RouterHome(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_RouterDemo_components_RouterHome_RouterHome
#endif
