// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: TicTacToe.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_TicTacToe_TicTacToe
{
struct FTicTacToeUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FTicTacToeUetkxProps& O = static_cast<const FTicTacToeUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode TicTacToe(FTicTacToeUetkxProps InProps = FTicTacToeUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_TicTacToe_TicTacToe
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_TicTacToe_TicTacToe
{
static FRuitkNodeArray TicTacToe_UetkxBody_08DE8C5C(FRuitkContext& Ctx, const FTicTacToeUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 2 "Source/RuitkDemo/Screens/TicTacToe/TicTacToe.uetkx"
	auto EmptyGrid = []() {
			TArray<FString> G;
			G.SetNum(9);
			return G;
		};
		auto [bStarted, SetStarted] = Ctx.UseState<bool>(false);
		auto [Turn, SetTurn] = Ctx.UseState<FString>(FString(TEXT("X")));
		auto [Grid, SetGrid] = Ctx.UseState<TArray<FString>>(EmptyGrid());
		auto [Winner, SetWinner] = Ctx.UseState<FString>(FString());
	
		auto Restart = [SetStarted, SetTurn, SetGrid, SetWinner, EmptyGrid]() {
			SetStarted(true);
			SetTurn(FString(TEXT("X")));
			SetWinner(FString());
			SetGrid(EmptyGrid());
		};
	
		auto CheckWinner = [](const TArray<FString>& G) -> FString {
			static const int32 Lines[8][3] = {{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {0, 3, 6},
												{1, 4, 7}, {2, 5, 8}, {0, 4, 8}, {2, 4, 6}};
			for (const int32* L : Lines)
			{
				if (!G[L[0]].IsEmpty() && G[L[0]] == G[L[1]] && G[L[0]] == G[L[2]])
				{
					return G[L[0]];
				}
			}
			return FString();
		};
	
		int32 MovesLeft = 0;
		for (const FString& Cell : Grid)
		{
			if (Cell.IsEmpty())
			{
				++MovesLeft;
			}
		}
	
		auto PlayCell = [SetGrid, SetTurn, SetWinner, CheckWinner, Grid, Turn, Winner](int32 Index) {
			if (!Winner.IsEmpty() || !Grid[Index].IsEmpty())
			{
				return;
			}
			TArray<FString> Next = Grid;
			Next[Index] = Turn;
			SetGrid(Next);
			const FString Win = CheckWinner(Next);
			if (!Win.IsEmpty())
			{
				SetWinner(Win);
			}
			else
			{
				SetTurn(Turn == TEXT("X") ? FString(TEXT("O")) : FString(TEXT("X")));
			}
		};
#line 85 "TicTacToe.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.TicTacToe", "TicTacToe_1", "Welcome to Tic Tac Toe!"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.4f, 0.8f, 1.0f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { Restart(); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((FText::FromString(bStarted ? TEXT("Restart Game") : TEXT("Start Game"))), FRuitkKey()));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		if (bStarted)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		if (!Winner.IsEmpty())
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("Player {} is the winner"), Winner)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(14.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.6f, 1.0f, 0.6f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		}
		else if (MovesLeft == 0)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.TicTacToe", "TicTacToe_2", "Draw!"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(14.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(1.0f, 0.8f, 0.4f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		}
		else
		{
			Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("Player turn: {}   (moves left: {})"), Turn, MovesLeft)), FRuitkKey()));
		}
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		for (int32 R = 0; R < 3; ++R)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		for (int32 C = 0; C < 3; ++C)
		{
			const int32 Index = R * 3 + C;
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((44.0f));
		P.SetHeightOverride((44.0f));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { PlayCell(Index); }));
		P.SetContentPadding(FMargin(0));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((FText::FromString(Grid[Index].IsEmpty() ? FString(TEXT(" ")) : Grid[Index])), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(1.0f, 0.85f, 0.4f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey(Index));
	}());
		}
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey(100 + R));
	}());
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray TicTacToe_UetkxImpl(FRuitkContext& Ctx, const FTicTacToeUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return TicTacToe_UetkxBody_08DE8C5C(Ctx, Props, children);
}
static const FName GTicTacToeUetkxId = Ruitk::RegisterComponentId((void*)&TicTacToe_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_TicTacToe_TicTacToe::TicTacToe")));
static constexpr uint32 TicTacToe_RUITK_HOOK_SIG = 0x62237E89u;
inline FRuitkNode TicTacToe(FTicTacToeUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&TicTacToe_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GTicTacToeUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_TicTacToe_TicTacToe::TicTacToe")), []() { return TicTacToe(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_TicTacToe_TicTacToe
#endif
