;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/RuitkDemo
DestinationPath=Content/Localization/RuitkDemo
ManifestName=RuitkDemo.manifest
ArchiveName=RuitkDemo.archive
NativeCulture=en
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=%LOCPROJECTROOT%Source/
SearchDirectoryPaths=%LOCPROJECTROOT%Plugins/ReactiveUIToolkit/Source/
ExcludePathFilters=Config/Localization/*
ExcludePathFilters=Source/RuitkHostTests/*
ExcludePathFilters=Plugins/ReactiveUIToolkit/Source/RuitkEditor/*
FileNameFilters=*.cpp
FileNameFilters=*.h
FileNameFilters=*.c
FileNameFilters=*.inl
FileNameFilters=*.ini

[GatherTextStep1]
CommandletClass=GenerateGatherManifest

[GatherTextStep2]
CommandletClass=GenerateGatherArchive
bPurgeOldEmptyEntries=true

[GatherTextStep3]
CommandletClass=GenerateTextLocalizationResource
ResourceName=RuitkDemo.locres

