// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: DemoContextPanel.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "RuitkDemoSupport.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_ContextDemo_components_DemoContextPanel_DemoContextPanel
{
struct FDemoContextPanelUetkxProps final : public FRuitkPropsBase
{
	FString Label = FString(TEXT("Primary Panel"));

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FDemoContextPanelUetkxProps& O = static_cast<const FDemoContextPanelUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (Label == O.Label);
		return bEq;
	}
};
inline FRuitkNode DemoContextPanel(FDemoContextPanelUetkxProps InProps = FDemoContextPanelUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_ContextDemo_components_DemoContextPanel_DemoContextPanel
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_ContextDemo_components_DemoContextPanel_DemoContextPanel
{
static FRuitkNodeArray DemoContextPanel_UetkxBody_5E1E4D68(FRuitkContext& Ctx, const FDemoContextPanelUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	const auto& Label = Props.Label;
#line 4 "Source/RuitkDemo/Screens/ContextDemo/components/DemoContextPanel/DemoContextPanel.uetkx"
	const FLinearColor Theme = Ctx.UseContext(RuitkDemo::GDemoThemeCtx);
#line 33 "DemoContextPanel.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(10));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((Theme));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,6,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((FText::FromString(FString::Printf(TEXT("%s: rgba(%.2f, %.2f, %.2f)"), *Label, Theme.R, Theme.G, Theme.B))), FRuitkKey()));
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray DemoContextPanel_UetkxImpl(FRuitkContext& Ctx, const FDemoContextPanelUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return DemoContextPanel_UetkxBody_5E1E4D68(Ctx, Props, children);
}
static const FName GDemoContextPanelUetkxId = Ruitk::RegisterComponentId((void*)&DemoContextPanel_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_ContextDemo_components_DemoContextPanel_DemoContextPanel::DemoContextPanel")));
static constexpr uint32 DemoContextPanel_RUITK_HOOK_SIG = 0x3A36D564u;
inline FRuitkNode DemoContextPanel(FDemoContextPanelUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&DemoContextPanel_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GDemoContextPanelUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_ContextDemo_components_DemoContextPanel_DemoContextPanel::DemoContextPanel")), []() { return DemoContextPanel(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_ContextDemo_components_DemoContextPanel_DemoContextPanel
#endif
