// AUTO-GENERATED by RUICompile — DO NOT EDIT. Source: AcceptanceLab.hooks.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUI_UETKX_DECL_PHASE)
namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_hooks
{
inline TTuple<int32, TFunction<void()>, TFunction<void()>> UseLabState(FRuiContext& Ctx, int32 Start);

} // namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_hooks
#else
namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_hooks
{
inline TTuple<int32, TFunction<void()>, TFunction<void()>> UseLabState(FRuiContext& Ctx, int32 Start)
{
#line 19 "Source/RuiDemo/Screens/AcceptanceLab/AcceptanceLab.hooks.uetkx"
	auto [Count, SetCount] = Ctx.UseState<int32>(Start);
		const int32 Current = Count;
		TFunction<void()> Increment = [SetCount, Current]() { SetCount(Current + 1); };
		TFunction<void()> Reset = [SetCount]() { SetCount(0); };
		return MakeTuple(Count, Increment, Reset);
#line 23 "AcceptanceLab.hooks.uetkx.inl"
}

} // namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_hooks
#endif
