// AUTO-GENERATED by RUICompile — DO NOT EDIT. Source: AcceptanceLab.style.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUI_UETKX_DECL_PHASE)
namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style
{
inline FLinearColor Accent()
{
	return
#line 12 "Source/RuiDemo/Screens/AcceptanceLab/AcceptanceLab.style.uetkx"
{ 0.36f, 0.75f, 1.0f, 1.0f }
#line 14 "AcceptanceLab.style.uetkx.inl"
;
}

inline FLinearColor Good()
{
	return
#line 13 "Source/RuiDemo/Screens/AcceptanceLab/AcceptanceLab.style.uetkx"
{ 0.45f, 0.90f, 0.50f, 1.0f }
#line 23 "AcceptanceLab.style.uetkx.inl"
;
}

inline FLinearColor Warn()
{
	return
#line 14 "Source/RuiDemo/Screens/AcceptanceLab/AcceptanceLab.style.uetkx"
{ 0.98f, 0.72f, 0.25f, 1.0f }
#line 32 "AcceptanceLab.style.uetkx.inl"
;
}

inline FLinearColor Panel()
{
	return
#line 15 "Source/RuiDemo/Screens/AcceptanceLab/AcceptanceLab.style.uetkx"
{ 0.02f, 0.02f, 0.03f, 0.85f }
#line 41 "AcceptanceLab.style.uetkx.inl"
;
}

} // namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style
#else
namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style
{
} // namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style
#endif
