// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: CustomDraw.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "RuitkDemoSupport.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_CustomDraw_CustomDraw
{
struct FCustomDrawUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FCustomDrawUetkxProps& O = static_cast<const FCustomDrawUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode CustomDraw(FCustomDrawUetkxProps InProps = FCustomDrawUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_CustomDraw_CustomDraw
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_CustomDraw_CustomDraw
{
static FRuitkNodeArray CustomDraw_UetkxBody_4DE9552F(FRuitkContext& Ctx, const FCustomDrawUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 4 "Source/RuitkDemo/Screens/CustomDraw/CustomDraw.uetkx"
	auto [Sides, SetSides] = Ctx.UseState<int32>(3);
		auto [bBlue, SetBlue] = Ctx.UseState<bool>(true);
		auto [RedrawTick, SetRedrawTick] = Ctx.UseState<int32>(0);
	
		// 1+2: the draw fn's IDENTITY tracks its inputs (UseMemo deps) -> repaint on change.
		const TSharedPtr<FRuitkDrawFn>& PolyFn = Ctx.UseMemo<TSharedPtr<FRuitkDrawFn>>(
			[Sides]() {
				return Ruitk::Slate::MakeDrawFn([Sides](const FGeometry& G, FSlateWindowElementList& O, int32 L)
												{ return RuitkDemo::DrawPolygon(G, O, L, Sides); });
			},
			Ruitk::Deps(Sides));
	
		const TSharedPtr<FRuitkDrawFn>& QuadFn = Ctx.UseMemo<TSharedPtr<FRuitkDrawFn>>(
			[bBlue]() {
				return Ruitk::Slate::MakeDrawFn([bBlue](const FGeometry& G, FSlateWindowElementList& O, int32 L)
												{ return RuitkDemo::DrawQuad(G, O, L, bBlue); });
			},
			Ruitk::Deps(bBlue));
	
		// 3: STABLE fn + RedrawKey bump forces the repaint instead.
		const TSharedPtr<FRuitkDrawFn>& ScatterFn =
			Ctx.UseMemo<TSharedPtr<FRuitkDrawFn>>([]() { return Ruitk::Slate::MakeDrawFn(&RuitkDemo::DrawScatter); }, Ruitk::Deps());
#line 51 "CustomDraw.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.CustomDraw", "CustomDraw_1", "Custom Rendering Demo (RuitkCanvas draw_fn)"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.4f, 0.8f, 1.0f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.CustomDraw", "CustomDraw_2", "1. Polygon -- redraws when 'sides' state changes"), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkCanvasProps P;
		P.SetDrawFn((PolyFn));
		P.SetCanvasSize((FVector2D(360.0f, 110.0f)));
		return Ruitk::Slate::RuitkCanvas(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetSides(Sides + 1); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.CustomDraw", "CustomDraw_3", "Add side")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetSides(3); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.CustomDraw", "CustomDraw_4", "Reset")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("  sides = {}"), Sides)), FRuitkKey()));
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.CustomDraw", "CustomDraw_5", "2. Tinted quad -- toggles color"), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkCanvasProps P;
		P.SetDrawFn((QuadFn));
		P.SetCanvasSize((FVector2D(360.0f, 110.0f)));
		return Ruitk::Slate::RuitkCanvas(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetBlue(!bBlue); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.CustomDraw", "CustomDraw_6", "Toggle color")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add(Ruitk::TextBlock((FText::FromString(bBlue ? TEXT("  blue") : TEXT("  orange"))), FRuitkKey()));
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.CustomDraw", "CustomDraw_7", "3. Stable callback + RedrawKey -- repaint on demand"), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkCanvasProps P;
		P.SetDrawFn((ScatterFn));
		P.SetRedrawKey((RedrawTick));
		P.SetCanvasSize((FVector2D(360.0f, 110.0f)));
		return Ruitk::Slate::RuitkCanvas(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetRedrawTick(RedrawTick + 1); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.CustomDraw", "CustomDraw_8", "Shuffle(bump RedrawKey)")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("  redrawKey = {}"), RedrawTick)), FRuitkKey()));
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray CustomDraw_UetkxImpl(FRuitkContext& Ctx, const FCustomDrawUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return CustomDraw_UetkxBody_4DE9552F(Ctx, Props, children);
}
static const FName GCustomDrawUetkxId = Ruitk::RegisterComponentId((void*)&CustomDraw_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_CustomDraw_CustomDraw::CustomDraw")));
static constexpr uint32 CustomDraw_RUITK_HOOK_SIG = 0x01D624F6u;
inline FRuitkNode CustomDraw(FCustomDrawUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&CustomDraw_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GCustomDrawUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_CustomDraw_CustomDraw::CustomDraw")), []() { return CustomDraw(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_CustomDraw_CustomDraw
#endif
