// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: HostImportProof.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "Misc/DateTime.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkHostTests_GrammarProof_HostImportProof
{
struct FHostImportProofUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FHostImportProofUetkxProps& O = static_cast<const FHostImportProofUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode HostImportProof(FHostImportProofUetkxProps InProps = FHostImportProofUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkHostTests_GrammarProof_HostImportProof
#else
namespace RuitkUetkx_Source_RuitkHostTests_GrammarProof_HostImportProof
{
static FRuitkNodeArray HostImportProof_UetkxBody_92A6E256(FRuitkContext& Ctx, const FHostImportProofUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 4 "Source/RuitkHostTests/GrammarProof/HostImportProof.uetkx"
	// FDateTime lives in Misc/DateTime.h — NOT on the auto-included prelude list
		// (INCLUDE_RETIREMENT_PLAN.md §A); reaching it here proves the `import "@Header.h"`
		// host include (§B) actually emits the #include the setup code needs.
		const FDateTime Stamp = FDateTime(2026, 1, 1);
		const FString Label = FString::Printf(TEXT("year=%d"), Stamp.GetYear());
#line 34 "HostImportProof.uetkx.inl"
	return { Ruitk::TextBlock((FString(Label)), FRuitkKey()) };
}
static FRuitkNodeArray HostImportProof_UetkxImpl(FRuitkContext& Ctx, const FHostImportProofUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return HostImportProof_UetkxBody_92A6E256(Ctx, Props, children);
}
static const FName GHostImportProofUetkxId = Ruitk::RegisterComponentId((void*)&HostImportProof_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkHostTests_GrammarProof_HostImportProof::HostImportProof")));
static constexpr uint32 HostImportProof_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode HostImportProof(FHostImportProofUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&HostImportProof_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GHostImportProofUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkHostTests_GrammarProof_HostImportProof::HostImportProof")), []() { return HostImportProof(); });

} // namespace RuitkUetkx_Source_RuitkHostTests_GrammarProof_HostImportProof
#endif
