// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: MultiReturnProof.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkHostTests_GrammarProof_MultiReturnProof
{
struct FMultiReturnProofUetkxProps final : public FRuitkPropsBase
{
	int32 Mode = 0;

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FMultiReturnProofUetkxProps& O = static_cast<const FMultiReturnProofUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (Mode == O.Mode);
		return bEq;
	}
};
inline FRuitkNode MultiReturnProof(FMultiReturnProofUetkxProps InProps = FMultiReturnProofUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

struct FMultiReturnProofEarlyUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FMultiReturnProofEarlyUetkxProps& O = static_cast<const FMultiReturnProofEarlyUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode MultiReturnProofEarly(FMultiReturnProofEarlyUetkxProps InProps = FMultiReturnProofEarlyUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

struct FMultiReturnProofBigUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FMultiReturnProofBigUetkxProps& O = static_cast<const FMultiReturnProofBigUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode MultiReturnProofBig(FMultiReturnProofBigUetkxProps InProps = FMultiReturnProofBigUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkHostTests_GrammarProof_MultiReturnProof
#else
namespace RuitkUetkx_Source_RuitkHostTests_GrammarProof_MultiReturnProof
{
static FRuitkNodeArray MultiReturnProof_UetkxBody_2CF1CBDE(FRuitkContext& Ctx, const FMultiReturnProofUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	const auto& Mode = Props.Mode;
#line 2 "Source/RuitkHostTests/GrammarProof/MultiReturnProof.uetkx"
	if (Mode == 1) {
#line 56 "MultiReturnProof.uetkx.inl"
	return { Ruitk::TextBlock(NSLOCTEXT("Uetkx.MultiReturnProof", "MultiReturnProof_1", "early-one"), FRuitkKey()) };
#line 4 "Source/RuitkHostTests/GrammarProof/MultiReturnProof.uetkx"
	}
		if (Mode == 2) {
#line 61 "MultiReturnProof.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.MultiReturnProof", "MultiReturnProof_2", "early-two"), FRuitkKey()));
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
#line 11 "Source/RuitkHostTests/GrammarProof/MultiReturnProof.uetkx"
	}
#line 70 "MultiReturnProof.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.MultiReturnProof", "MultiReturnProof_3", "main"), FRuitkKey()));
		Ch.Add((Mode > 10  ? Ruitk::TextBlock(NSLOCTEXT("Uetkx.MultiReturnProof", "MultiReturnProof_4", "big-mode"), FRuitkKey()) : FRuitkNode()));
		Ch.Add((Mode > 10  ? FRuitkNode() : Ruitk::TextBlock(NSLOCTEXT("Uetkx.MultiReturnProof", "MultiReturnProof_5", "small-mode"), FRuitkKey())));
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray MultiReturnProof_UetkxImpl(FRuitkContext& Ctx, const FMultiReturnProofUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return MultiReturnProof_UetkxBody_2CF1CBDE(Ctx, Props, children);
}
static const FName GMultiReturnProofUetkxId = Ruitk::RegisterComponentId((void*)&MultiReturnProof_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkHostTests_GrammarProof_MultiReturnProof::MultiReturnProof")));
static constexpr uint32 MultiReturnProof_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode MultiReturnProof(FMultiReturnProofUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&MultiReturnProof_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GMultiReturnProofUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkHostTests_GrammarProof_MultiReturnProof::MultiReturnProof")), []() { return MultiReturnProof(); });

static FRuitkNodeArray MultiReturnProofEarly_UetkxBody_2CF1CBDE(FRuitkContext& Ctx, const FMultiReturnProofEarlyUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return { [&]() -> FRuitkNode {
		FMultiReturnProofUetkxProps P;
		P.Mode = 1;
		TArray<FRuitkNode> Ch;
		return MultiReturnProof(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray MultiReturnProofEarly_UetkxImpl(FRuitkContext& Ctx, const FMultiReturnProofEarlyUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return MultiReturnProofEarly_UetkxBody_2CF1CBDE(Ctx, Props, children);
}
static const FName GMultiReturnProofEarlyUetkxId = Ruitk::RegisterComponentId((void*)&MultiReturnProofEarly_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkHostTests_GrammarProof_MultiReturnProof::MultiReturnProofEarly")));
static constexpr uint32 MultiReturnProofEarly_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode MultiReturnProofEarly(FMultiReturnProofEarlyUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&MultiReturnProofEarly_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GMultiReturnProofEarlyUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkHostTests_GrammarProof_MultiReturnProof::MultiReturnProofEarly")), []() { return MultiReturnProofEarly(); });

static FRuitkNodeArray MultiReturnProofBig_UetkxBody_2CF1CBDE(FRuitkContext& Ctx, const FMultiReturnProofBigUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return { [&]() -> FRuitkNode {
		FMultiReturnProofUetkxProps P;
		P.Mode = 20;
		TArray<FRuitkNode> Ch;
		return MultiReturnProof(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray MultiReturnProofBig_UetkxImpl(FRuitkContext& Ctx, const FMultiReturnProofBigUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return MultiReturnProofBig_UetkxBody_2CF1CBDE(Ctx, Props, children);
}
static const FName GMultiReturnProofBigUetkxId = Ruitk::RegisterComponentId((void*)&MultiReturnProofBig_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkHostTests_GrammarProof_MultiReturnProof::MultiReturnProofBig")));
static constexpr uint32 MultiReturnProofBig_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode MultiReturnProofBig(FMultiReturnProofBigUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&MultiReturnProofBig_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GMultiReturnProofBigUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkHostTests_GrammarProof_MultiReturnProof::MultiReturnProofBig")), []() { return MultiReturnProofBig(); });

} // namespace RuitkUetkx_Source_RuitkHostTests_GrammarProof_MultiReturnProof
#endif
