// AUTO-GENERATED by RUICompile — DO NOT EDIT. Source: SimpleCounter.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUI_UETKX_DECL_PHASE)
struct FSimpleCounterUetkxProps final : public FRuiPropsBase
{

	virtual bool Equals(const FRuiPropsBase& OtherBase) const override
	{
		const FSimpleCounterUetkxProps& O = static_cast<const FSimpleCounterUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuiNode SimpleCounter(FSimpleCounterUetkxProps InProps = FSimpleCounterUetkxProps(), TArray<FRuiNode> InChildren = TArray<FRuiNode>(), FRuiKey InKey = FRuiKey());

#else
static FRuiNodeArray SimpleCounter_UetkxImpl(FRuiContext& Ctx, const FSimpleCounterUetkxProps& Props, const TArray<FRuiNode>& children)
{
#line 5 "Source/RuiDemo/Screens/SimpleCounter/SimpleCounter.uetkx"
	// const FString& Title = UseMemo<FString>([]() { return FString(TEXT("DOOM COUNTERaaaaaaaaaaaa")); }, RUI::Deps());
		auto [Count, Increment] = UseCounter(Ctx, 0);
		auto [Count2, Increment2] = Ctx.UseState<int32>(0);
#line 26 "SimpleCounter.uetkx.inl"
	return { [&]() -> FRuiNode {
		FRuiBorderProps P;
		P.SetPadding((PanelPadding()));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((CounterPanelBackground()));
		TSharedRef<FRuiStyleDict> __Style = MakeShared<FRuiStyleDict>();
		TSharedRef<FRuiStyleDict> __Slot = MakeShared<FRuiStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuiValue(PanelSlotPadding()));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuiNode> Ch;
		Ch.Add([&]() -> FRuiNode {
		FRuiVerticalBoxProps P;
		TArray<FRuiNode> Ch;
		Ch.Add(RUI::TextBlock((FText::FromString(TEXT("DOOM COUNTERaaaaaaaaaaaa"))), FRuiKey()));
		Ch.Add(RUI::TextBlock((RUI::Fmt(TEXT("Count1: {}"), Count)), FRuiKey()));
		Ch.Add(RUI::TextBlock((RUI::Fmt(TEXT("Count2: {}"), Count2)), FRuiKey()));
		Ch.Add([&]() -> FRuiNode {
		FRuiSpacerProps P;
		P.SetSize((RowGap()));
		return RUI::Slate::Spacer(MoveTemp(P), FRuiKey());
	}());
		Ch.Add([&]() -> FRuiNode {
		FRuiHorizontalBoxProps P;
		TArray<FRuiNode> Ch;
		Ch.Add([&]() -> FRuiNode {
		FRuiButtonProps P;
		P.SetOnClicked(FRuiCallback::Create([=](const FRuiValue& Value) { Increment(); }));
		P.SetContentPadding((ButtonPadding()));
		TSharedRef<FRuiStyleDict> __Style = MakeShared<FRuiStyleDict>();
		TSharedRef<FRuiStyleDict> __Slot = MakeShared<FRuiStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuiValue(ButtonSlotPadding()));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuiNode> Ch;
		Ch.Add(RUI::TextBlock(NSLOCTEXT("Uetkx.SimpleCounter", "SimpleCounter_1", "+")));
		return RUI::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}());
		return RUI::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}());
		Ch.Add([&]() -> FRuiNode {
		FRuiHorizontalBoxProps P;
		TArray<FRuiNode> Ch;
		Ch.Add([&]() -> FRuiNode {
		FRuiButtonProps P;
		P.SetOnClicked(FRuiCallback::Create([=](const FRuiValue& Value) { Increment2([](const int32& Prev) { return Prev + 1; }); }));
		P.SetContentPadding((ButtonPadding()));
		TSharedRef<FRuiStyleDict> __Style = MakeShared<FRuiStyleDict>();
		TSharedRef<FRuiStyleDict> __Slot = MakeShared<FRuiStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuiValue(ButtonSlotPadding()));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuiNode> Ch;
		Ch.Add(RUI::TextBlock(NSLOCTEXT("Uetkx.SimpleCounter", "SimpleCounter_2", "+")));
		return RUI::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}());
		return RUI::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}());
		return RUI::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}());
		return RUI::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}() };
}
static const FName GSimpleCounterUetkxId = RUI::RegisterComponentId((void*)&SimpleCounter_UetkxImpl, FName(TEXT("SimpleCounter")));
static constexpr uint32 SimpleCounter_RUI_HOOK_SIG = 0x986DF5F6u;
inline FRuiNode SimpleCounter(FSimpleCounterUetkxProps InProps, TArray<FRuiNode> InChildren, FRuiKey InKey)
{
	return RUI::FC(&SimpleCounter_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GSimpleCounterUetkxFactoryReg = RUI::RegisterNamedFactory(FName(TEXT("SimpleCounter")), []() { return SimpleCounter(); });

#endif
