// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: ShowcaseProbe.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_InteropShowcase_components_ShowcaseProbe_ShowcaseProbe
{
struct FShowcaseProbeUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FShowcaseProbeUetkxProps& O = static_cast<const FShowcaseProbeUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode ShowcaseProbe(FShowcaseProbeUetkxProps InProps = FShowcaseProbeUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_InteropShowcase_components_ShowcaseProbe_ShowcaseProbe
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_InteropShowcase_components_ShowcaseProbe_ShowcaseProbe
{
static FRuitkNodeArray ShowcaseProbe_UetkxBody_458742CC(FRuitkContext& Ctx, const FShowcaseProbeUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 3 "Source/RuitkDemo/Screens/InteropShowcase/components/ShowcaseProbe/ShowcaseProbe.uetkx"
	const bool bActive = Ruitk::CommonUI::UseIsActive(Ctx);
#line 29 "ShowcaseProbe.uetkx.inl"
	return { Ruitk::TextBlock((Ruitk::Fmt(TEXT("screen is {}"), bActive ? TEXT("ACTIVE") : TEXT("INACTIVE"))), FRuitkKey()) };
}
static FRuitkNodeArray ShowcaseProbe_UetkxImpl(FRuitkContext& Ctx, const FShowcaseProbeUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return ShowcaseProbe_UetkxBody_458742CC(Ctx, Props, children);
}
static const FName GShowcaseProbeUetkxId = Ruitk::RegisterComponentId((void*)&ShowcaseProbe_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_InteropShowcase_components_ShowcaseProbe_ShowcaseProbe::ShowcaseProbe")));
static constexpr uint32 ShowcaseProbe_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode ShowcaseProbe(FShowcaseProbeUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&ShowcaseProbe_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GShowcaseProbeUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_InteropShowcase_components_ShowcaseProbe_ShowcaseProbe::ShowcaseProbe")), []() { return ShowcaseProbe(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_InteropShowcase_components_ShowcaseProbe_ShowcaseProbe
#endif
