// AUTO-GENERATED aggregator - DO NOT EDIT. Regenerated by RuitkCompile; the
// compiled source-file SET stays constant, only these contents change (D-19).
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "CoreMinimal.h"
#include "RuitkContext.h"
#include "RuitkCoreElements.h"
#include "RuitkSignal.h"
#include "RuitkSlateElements.h"
#include "RuitkStyle.h"
#include "RuitkRouter.h"
#if __has_include("RuitkAssetBrush.h")
#include "RuitkAssetBrush.h"
#endif
#if __has_include("RuitkFieldHooks.h")
#include "RuitkFieldHooks.h"
#endif
#if __has_include("RuitkUmgElement.h")
#include "RuitkUmgElement.h"
#endif
#if __has_include("RuitkSignalViewModel.h")
#include "RuitkSignalViewModel.h"
#endif
#if __has_include("RuitkHostWidget.h")
#include "RuitkHostWidget.h"
#endif
#if __has_include("RuitkWorldSubsystem.h")
#include "RuitkWorldSubsystem.h"
#endif
#if __has_include("RuitkActivation.h")
#include "RuitkActivation.h"
#endif
#if __has_include("RuitkActivatableScreen.h")
#include "RuitkActivatableScreen.h"
#endif
#if __has_include("RuitkMvvmViewModel.h")
#include "RuitkMvvmViewModel.h"
#endif
#if __has_include("UObject/StrongObjectPtr.h")
#include "UObject/StrongObjectPtr.h"
#endif
#if __has_include("Engine/World.h")
#include "Engine/World.h"
#endif

#define RUITK_UETKX_DECL_PHASE
#include "../ChildrenProof/ChildHost.uetkx.inl"
#include "../ChildrenProof/ChildParent.uetkx.inl"
#include "../GrammarProof/HostImportProof.uetkx.inl"
#include "../GrammarProof/MultiReturnProof.uetkx.inl"
#include "../CycleProof/CycleA.uetkx.inl"
#include "../CycleProof/CycleB.uetkx.inl"
#undef RUITK_UETKX_DECL_PHASE
#include "../ChildrenProof/ChildHost.uetkx.inl"
#include "../ChildrenProof/ChildParent.uetkx.inl"
#include "../GrammarProof/HostImportProof.uetkx.inl"
#include "../GrammarProof/MultiReturnProof.uetkx.inl"
#include "../CycleProof/CycleA.uetkx.inl"
#include "../CycleProof/CycleB.uetkx.inl"
