// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: DoomHUD.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "Doom/DoomTypes.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomHUD_DoomHUD
{
struct FDoomHUDUetkxProps final : public FRuitkPropsBase
{
	int32 Health = 100;
	int32 Armor = 0;
	int32 ArmorClass = 0;
	RuitkDoom::EWeaponType Weapon = RuitkDoom::EWeaponType::Pistol;
	TArray<int32> Ammo = TArray<int32>();
	TArray<bool> OwnedWeapons = TArray<bool>();
	RuitkDoom::EKeyCard Keys = RuitkDoom::EKeyCard::None;
	int32 Score = 0;
	int32 KillCount = 0;
	int32 KillTotal = 0;
	FString MapName = FString();
	int32 FaceState = 0;

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FDoomHUDUetkxProps& O = static_cast<const FDoomHUDUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (Health == O.Health);
		bEq = bEq && (Armor == O.Armor);
		bEq = bEq && (ArmorClass == O.ArmorClass);
		bEq = bEq && (Weapon == O.Weapon);
		bEq = bEq && (Ammo == O.Ammo);
		bEq = bEq && (OwnedWeapons == O.OwnedWeapons);
		bEq = bEq && (Keys == O.Keys);
		bEq = bEq && (Score == O.Score);
		bEq = bEq && (KillCount == O.KillCount);
		bEq = bEq && (KillTotal == O.KillTotal);
		bEq = bEq && (MapName == O.MapName);
		bEq = bEq && (FaceState == O.FaceState);
		return bEq;
	}
};
inline FRuitkNode DoomHUD(FDoomHUDUetkxProps InProps = FDoomHUDUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomHUD_DoomHUD
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomHUD_DoomHUD
{
static FRuitkNodeArray DoomHUD_UetkxBody_028C5E33(FRuitkContext& Ctx, const FDoomHUDUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	const auto& Health = Props.Health;
	const auto& Armor = Props.Armor;
	const auto& ArmorClass = Props.ArmorClass;
	const auto& Weapon = Props.Weapon;
	const auto& Ammo = Props.Ammo;
	const auto& OwnedWeapons = Props.OwnedWeapons;
	const auto& Keys = Props.Keys;
	const auto& Score = Props.Score;
	const auto& KillCount = Props.KillCount;
	const auto& KillTotal = Props.KillTotal;
	const auto& MapName = Props.MapName;
	const auto& FaceState = Props.FaceState;
#line 11 "Source/RuitkDemo/Screens/DoomDemo/components/DoomHUD/DoomHUD.uetkx"
	const FLinearColor BarBg(0.12f, 0.10f, 0.08f, 1.0f);
		const FLinearColor PanelBg(0.20f, 0.16f, 0.10f, 1.0f);
		const FLinearColor TopBorder(0.85f, 0.55f, 0.20f, 1.0f);
		const FLinearColor RedNum(0.95f, 0.20f, 0.15f, 1.0f);
		const FLinearColor LabelClr(0.85f, 0.70f, 0.35f, 1.0f);
		const FLinearColor DimClr(0.45f, 0.40f, 0.30f, 1.0f);
		const FLinearColor DotBorder(0.4f, 0.4f, 0.4f, 1.0f);
	
		static const TCHAR* AmmoLabels[] = {TEXT("BUL"), TEXT("SHL"), TEXT("RKT"), TEXT("CEL")};
		const int32 AmmoMax[] = {RuitkDoom::C::MAX_BULLETS, RuitkDoom::C::MAX_SHELLS, RuitkDoom::C::MAX_ROCKETS,
									RuitkDoom::C::MAX_CELLS};
	
		// Current-weapon ammo readout (the Unity CurrentAmmoLabel switch, verbatim mapping).
		auto AmmoAt = [&](int32 i) { return Ammo.IsValidIndex(i) ? Ammo[i] : 0; };
		FString CurrentAmmo;
		switch (Weapon)
		{
		case RuitkDoom::EWeaponType::Pistol:
		case RuitkDoom::EWeaponType::Chaingun:
			CurrentAmmo = FString::FromInt(AmmoAt(0));
			break;
		case RuitkDoom::EWeaponType::Shotgun:
			CurrentAmmo = FString::FromInt(AmmoAt(1));
			break;
		case RuitkDoom::EWeaponType::RocketLauncher:
			CurrentAmmo = FString::FromInt(AmmoAt(2));
			break;
		case RuitkDoom::EWeaponType::PlasmaRifle:
		case RuitkDoom::EWeaponType::BFG9000:
			CurrentAmmo = FString::FromInt(AmmoAt(3));
			break;
		default:
			CurrentAmmo = TEXT("—");
			break;
		}
	
		// Key-card dot colors: full color when owned, 15% dim when not (Unity KeyDot).
		const FLinearColor BlueKey(0.30f, 0.55f, 1.00f, 1.0f);
		const FLinearColor YellowKey(0.95f, 0.85f, 0.20f, 1.0f);
		const FLinearColor RedKey(0.95f, 0.20f, 0.20f, 1.0f);
		auto KeyOff = [](const FLinearColor& C) { return FLinearColor(C.R * 0.15f, C.G * 0.15f, C.B * 0.15f, 1.0f); };
		const bool bHasBlue = EnumHasAnyFlags(Keys, RuitkDoom::EKeyCard::Blue);
		const bool bHasYellow = EnumHasAnyFlags(Keys, RuitkDoom::EKeyCard::Yellow);
		const bool bHasRed = EnumHasAnyFlags(Keys, RuitkDoom::EKeyCard::Red);
#line 109 "DoomHUD.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((static_cast<float>(RuitkDoom::C::VIEWPORT_W)));
		P.SetHeightOverride((static_cast<float>(RuitkDoom::C::HUD_HEIGHT)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((TopBorder));
		P.SetPadding(FMargin(0,3,0,0));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((BarBg));
		P.SetPadding(FMargin(8,6));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((TopBorder));
		P.SetPadding(FMargin(1));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Fill")), FRuitkValue(2.0f));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,4,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((PanelBg));
		P.SetPadding(FMargin(6,4));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomHUD", "DoomHUD_1", "AMMO"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(10.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(LabelClr));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((FText::FromString(CurrentAmmo)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(24.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RedNum));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,4,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((TopBorder));
		P.SetPadding(FMargin(1));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Fill")), FRuitkValue(2.5f));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,4,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((PanelBg));
		P.SetPadding(FMargin(6,4));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomHUD", "DoomHUD_2", "HEALTH"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(10.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(LabelClr));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("{}%"), Health)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(24.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RedNum));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,4,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((TopBorder));
		P.SetPadding(FMargin(1));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Fill")), FRuitkValue(3.0f));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,4,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((PanelBg));
		P.SetPadding(FMargin(6,4));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomHUD", "DoomHUD_3", "ARMS"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(10.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(LabelClr));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkWrapBoxProps P;
		P.SetbUseAllottedSize((true));
		P.SetInnerSlotPadding((FVector2D(2.0f, 1.0f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		for (int32 i = 1; i <= 6; ++i)
		{
			const bool bOwned = OwnedWeapons.IsValidIndex(i) && OwnedWeapons[i];
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((20.0f));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("{}"), i + 1)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(bOwned ? RedNum : DimClr));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(*FString::Printf(TEXT("arm%d"), i))));
	}());
		}
		return Ruitk::Slate::WrapBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomFace_DoomFace::FDoomFaceUetkxProps P;
		P.Frame = FaceState;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomFace_DoomFace::DoomFace(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((TopBorder));
		P.SetPadding(FMargin(1));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Fill")), FRuitkValue(2.5f));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,4,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((PanelBg));
		P.SetPadding(FMargin(6,4));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((ArmorClass == 2 ? INVTEXT("MEGA") : INVTEXT("ARMOR")), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(10.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(LabelClr));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("{}%"), Armor)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(24.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RedNum));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,4,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((TopBorder));
		P.SetPadding(FMargin(1));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Fill")), FRuitkValue(0.8f));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,4,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((PanelBg));
		P.SetPadding(FMargin(6,4));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((14.0f));
		P.SetHeightOverride((14.0f));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,0,2")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((DotBorder));
		P.SetPadding(FMargin(1));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((bHasBlue ? BlueKey : KeyOff(BlueKey)));
		TArray<FRuitkNode> Ch;
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((14.0f));
		P.SetHeightOverride((14.0f));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,0,2")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((DotBorder));
		P.SetPadding(FMargin(1));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((bHasYellow ? YellowKey : KeyOff(YellowKey)));
		TArray<FRuitkNode> Ch;
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((14.0f));
		P.SetHeightOverride((14.0f));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,0,2")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((DotBorder));
		P.SetPadding(FMargin(1));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((bHasRed ? RedKey : KeyOff(RedKey)));
		TArray<FRuitkNode> Ch;
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((TopBorder));
		P.SetPadding(FMargin(1));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Fill")), FRuitkValue(3.5f));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,4,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((PanelBg));
		P.SetPadding(FMargin(6,4));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		for (int32 i = 0; i < 4; ++i)
		{
			const int32 Have = Ammo.IsValidIndex(i) ? Ammo[i] : 0;
			Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,0,1")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((FText::FromString(AmmoLabels[i])), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(10.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(LabelClr));
		__Slot->Add(FName(TEXT("Slot.Fill")), FRuitkValue(1.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("{} / {}"), Have, AmmoMax[i])), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RedNum));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(*FString::Printf(TEXT("a%d"), i))));
	}());
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((TopBorder));
		P.SetPadding(FMargin(1));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Fill")), FRuitkValue(4.0f));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((PanelBg));
		P.SetPadding(FMargin(6,4));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((FText::FromString(MapName)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(10.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(LabelClr));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,4")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("KILLS  {} / {}"), KillCount, KillTotal)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(12.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RedNum));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("SCORE  {}"), Score)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(12.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RedNum));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,2,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray DoomHUD_UetkxImpl(FRuitkContext& Ctx, const FDoomHUDUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return DoomHUD_UetkxBody_028C5E33(Ctx, Props, children);
}
static const FName GDoomHUDUetkxId = Ruitk::RegisterComponentId((void*)&DoomHUD_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomHUD_DoomHUD::DoomHUD")));
static constexpr uint32 DoomHUD_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode DoomHUD(FDoomHUDUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&DoomHUD_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GDoomHUDUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomHUD_DoomHUD::DoomHUD")), []() { return DoomHUD(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomHUD_DoomHUD
#endif
