// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: UmgHostDemo.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "RuitkDemoSupport.h"
#include "DemoInteropWidgets.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_UmgHostDemo
{
struct FUmgHostDemoUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FUmgHostDemoUetkxProps& O = static_cast<const FUmgHostDemoUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode UmgHostDemo(FUmgHostDemoUetkxProps InProps = FUmgHostDemoUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_UmgHostDemo
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_UmgHostDemo
{
static FRuitkNodeArray UmgHostDemo_UetkxBody_08102C9D(FRuitkContext& Ctx, const FUmgHostDemoUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 10 "Source/RuitkDemo/Screens/UmgHostDemo/UmgHostDemo.uetkx"
	UWorld* World = RuitkDemo::GetDemoWorld();
		URuitkSignalViewModel* Vm = RuitkDemo::GetSharedVm();
		const int32 N = Ruitk::Umg::UseField<int32>(Ctx, Vm, FName(TEXT("Int")), 0);
#line 33 "UmgHostDemo.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.UmgHostDemo", "UmgHostDemo_1", "UMG -- the door's second direction, and the reverse MVVM bridge"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 8.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.UmgHostDemo", "UmgHostDemo_2", "1. OUR UI INSIDE THEIRS -- URuitkHostWidget in a hand-built UserWidget:"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add((World ? Ruitk::Umg::UserWidget(UDemoHostUserWidget::StaticClass(), World) : Ruitk::TextBlock(FString(TEXT("[press Play -- the UMG host needs a running world]")))));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 12.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.UmgHostDemo", "UmgHostDemo_3", "2. THEIR VIEW ON OUR STATE -- a UMG TextBlock FieldNotify-bound to our viewmodel:"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add((World ? Ruitk::Umg::UserWidget(UDemoVmBoundWidget::StaticClass(), World) : Ruitk::TextBlock(FString(TEXT("[press Play -- the bound widget needs a running world]")))));
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("▼ our UseField reads the same field: {}"), N)), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { Vm->SetInt(N + 1); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,4,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.UmgHostDemo", "UmgHostDemo_4", "our code writes: viewmodel.SetInt(+1)")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray UmgHostDemo_UetkxImpl(FRuitkContext& Ctx, const FUmgHostDemoUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return UmgHostDemo_UetkxBody_08102C9D(Ctx, Props, children);
}
static const FName GUmgHostDemoUetkxId = Ruitk::RegisterComponentId((void*)&UmgHostDemo_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_UmgHostDemo::UmgHostDemo")));
static constexpr uint32 UmgHostDemo_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode UmgHostDemo(FUmgHostDemoUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&UmgHostDemo_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GUmgHostDemoUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_UmgHostDemo::UmgHostDemo")), []() { return UmgHostDemo(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_UmgHostDemo_UmgHostDemo
#endif
