// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: KeyedDiff.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_KeyedDiff_KeyedDiff
{
struct FKeyedDiffUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FKeyedDiffUetkxProps& O = static_cast<const FKeyedDiffUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode KeyedDiff(FKeyedDiffUetkxProps InProps = FKeyedDiffUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_KeyedDiff_KeyedDiff
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_KeyedDiff_KeyedDiff
{
static FRuitkNodeArray KeyedDiff_UetkxBody_A51DA7A5(FRuitkContext& Ctx, const FKeyedDiffUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 2 "Source/RuitkDemo/Screens/KeyedDiff/KeyedDiff.uetkx"
	static const TCHAR* Seed[] = {TEXT("Alpha"), TEXT("Bravo"), TEXT("Charlie"), TEXT("Delta"),
										TEXT("Echo"), TEXT("Foxtrot"), TEXT("Golf")};
		auto SeedItems = []() {
			TArray<FString> Out;
			for (const TCHAR* S : Seed)
			{
				Out.Add(S);
			}
			return Out;
		};
	
		auto [Items, SetItems] = Ctx.UseState<TArray<FString>>(SeedItems());
		auto [Ops, SetOps] = Ctx.UseState<int32>(0);
		auto [NextId, SetNextId] = Ctx.UseState<int32>(1);
	
		auto Apply = [SetItems, SetOps, Ops](TArray<FString> Next) {
			SetItems(MoveTemp(Next));
			SetOps(Ops + 1);
		};
		auto DoReset = [SetItems, SetOps, SeedItems]() {
			SetItems(SeedItems());
			SetOps(0);
		};
		auto DoReverse = [Apply, Items]() {
			TArray<FString> Next = Items;
			Algo::Reverse(Next);
			Apply(MoveTemp(Next));
		};
		auto DoRotate = [Apply, Items]() {
			if (!Items.IsEmpty())
			{
				TArray<FString> Next;
				Next.Add(Items.Last());
				for (int32 i = 0; i < Items.Num() - 1; ++i)
				{
					Next.Add(Items[i]);
				}
				Apply(MoveTemp(Next));
			}
		};
		auto DoShuffle = [Apply, Items, Ops]() {
			TArray<FString> Next = Items;
			FRandomStream Rng(Ops * 7919 + Next.Num());
			for (int32 i = Next.Num() - 1; i > 0; --i)
			{
				Next.Swap(i, Rng.RandRange(0, i));
			}
			Apply(MoveTemp(Next));
		};
		auto DoInsert = [Apply, Items, NextId, SetNextId]() {
			TArray<FString> Next = Items;
			FRandomStream Rng(NextId * 31 + Next.Num());
			Next.Insert(FString::Printf(TEXT("New-%d"), NextId), Next.IsEmpty() ? 0 : Rng.RandRange(0, Next.Num() - 1));
			SetNextId(NextId + 1);
			Apply(MoveTemp(Next));
		};
		auto DoRemove = [Apply, Items]() {
			if (!Items.IsEmpty())
			{
				TArray<FString> Next = Items;
				Next.RemoveAt(Next.Num() / 2);
				Apply(MoveTemp(Next));
			}
		};
#line 92 "KeyedDiff.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.KeyedDiff", "KeyedDiff_1", "Keyed diff / LIS test"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(1.0f, 0.8f, 0.4f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.KeyedDiff", "KeyedDiff_2", "Reorder, insert, and remove keyed rows -- rows stay mounted while order changes."), FRuitkKey()));
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("Operations performed: {}"), Ops)), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { DoReset(); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.KeyedDiff", "KeyedDiff_3", "Reset")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { DoReverse(); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.KeyedDiff", "KeyedDiff_4", "Reverse")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { DoRotate(); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.KeyedDiff", "KeyedDiff_5", "Rotate tail to head")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { DoShuffle(); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.KeyedDiff", "KeyedDiff_6", "Shuffle")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { DoInsert(); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.KeyedDiff", "KeyedDiff_7", "Insert new key")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { DoRemove(); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.KeyedDiff", "KeyedDiff_8", "Remove middle")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		for (int32 i = 0; i < Items.Num(); ++i)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("Key: {}"), Items[i])), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("   Index {}"), i)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(9.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.3f, 0.9f, 0.9f)));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("10,0,0,0")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(*Items[i])));
	}());
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray KeyedDiff_UetkxImpl(FRuitkContext& Ctx, const FKeyedDiffUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return KeyedDiff_UetkxBody_A51DA7A5(Ctx, Props, children);
}
static const FName GKeyedDiffUetkxId = Ruitk::RegisterComponentId((void*)&KeyedDiff_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_KeyedDiff_KeyedDiff::KeyedDiff")));
static constexpr uint32 KeyedDiff_RUI_HOOK_SIG = 0xDDEFCD0Cu;
inline FRuitkNode KeyedDiff(FKeyedDiffUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&KeyedDiff_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GKeyedDiffUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_KeyedDiff_KeyedDiff::KeyedDiff")), []() { return KeyedDiff(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_KeyedDiff_KeyedDiff
#endif
