// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: StressTest.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "RuitkDemoSupport.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_StressTest_StressTest
{
struct FStressTestUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FStressTestUetkxProps& O = static_cast<const FStressTestUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode StressTest(FStressTestUetkxProps InProps = FStressTestUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_StressTest_StressTest
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_StressTest_StressTest
{
static FRuitkNodeArray StressTest_UetkxBody_59AC27E6(FRuitkContext& Ctx, const FStressTestUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 4 "Source/RuitkDemo/Screens/StressTest/StressTest.uetkx"
	auto [CountText, SetCountText] = Ctx.UseState<FString>(FString(TEXT("300")));
		auto [DurationText, SetDurationText] = Ctx.UseState<FString>(FString(TEXT("10")));
		auto [bRunning, SetRunning] = Ctx.UseState<bool>(false);
		auto [Version, SetVersion] = Ctx.UseState<int32>(0);
		auto [Stats, SetStats] = Ctx.UseState<RuitkDemo::FStressStats>(RuitkDemo::FStressStats());
		auto [RenderTick, SetRenderTick] = Ctx.UseState<int32>(0);
		(void)RenderTick; // consumed implicitly: each bump re-renders the box field below
	
		// Simulation state lives OUTSIDE render state (mutated per tick, read by render).
		TSharedRef<TRuitkRef<TArray<RuitkDemo::FStressBox>>> Boxes = Ctx.UseRef<TArray<RuitkDemo::FStressBox>>();
	
		IRuitkHostConfig* Host = &Ctx.GetHost();
	
		// The frame loop: a self-re-arming RequestFrame chain (the Suspense poll-driver pattern).
		Ctx.UseEffect(
			[bRunning, CountText, DurationText, Boxes, Host, SetStats, SetRenderTick, SetRunning,
				Version]() -> TFunction<void()> {
				if (!bRunning)
				{
					return []() {};
				}
				const int32 Count = FMath::Clamp(FCString::Atoi(*CountText), 1, 10000);
				const float Duration = FMath::Clamp(FCString::Atof(*DurationText), 1.0f, 600.0f);
	
				TArray<RuitkDemo::FStressBox>& B = Boxes->Current;
				B.Reset(Count);
				FRandomStream Rng(Version * 7919 + Count);
				for (int32 i = 0; i < Count; ++i)
				{
					RuitkDemo::FStressBox Box;
					Box.Id = i;
					Box.Size = Rng.FRandRange(6.0f, 18.0f);
					Box.Pos = FVector2D(Rng.FRandRange(0.0f, RuitkDemo::StressAreaW - Box.Size),
										Rng.FRandRange(0.0f, RuitkDemo::StressAreaH - Box.Size));
					Box.Vel = FVector2D(Rng.FRandRange(-120.0f, 120.0f), Rng.FRandRange(-120.0f, 120.0f));
					Box.Color = FLinearColor::MakeFromHSV8(static_cast<uint8>(Rng.RandRange(0, 255)), 180, 230);
					B.Add(Box);
				}
	
				TSharedRef<bool> Cancelled = MakeShared<bool>(false);
				TSharedRef<double> Start = MakeShared<double>(FPlatformTime::Seconds());
				TSharedRef<double> Last = MakeShared<double>(*Start);
				TSharedRef<int32> Frames = MakeShared<int32>(0);
				TSharedRef<int32> Tick = MakeShared<int32>(0);
	
				TSharedRef<TFunction<void()>> Loop = MakeShared<TFunction<void()>>();
				*Loop = [Cancelled, Start, Last, Frames, Tick, Boxes, Host, Duration, SetStats, SetRenderTick,
							SetRunning, Loop]() {
					if (*Cancelled)
					{
						return;
					}
					const double Now = FPlatformTime::Seconds();
					const float Dt = FMath::Min(static_cast<float>(Now - *Last), 0.05f);
					*Last = Now;
					++(*Frames);
					for (RuitkDemo::FStressBox& Box : Boxes->Current)
					{
						Box.Pos += Box.Vel * Dt;
						if (Box.Pos.X < 0.0f || Box.Pos.X > RuitkDemo::StressAreaW - Box.Size)
						{
							Box.Vel.X *= -1.0f;
							Box.Pos.X = FMath::Clamp<double>(Box.Pos.X, 0.0, RuitkDemo::StressAreaW - Box.Size);
						}
						if (Box.Pos.Y < 0.0f || Box.Pos.Y > RuitkDemo::StressAreaH - Box.Size)
						{
							Box.Vel.Y *= -1.0f;
							Box.Pos.Y = FMath::Clamp<double>(Box.Pos.Y, 0.0, RuitkDemo::StressAreaH - Box.Size);
						}
					}
					const float Elapsed = static_cast<float>(Now - *Start);
					RuitkDemo::FStressStats S;
					S.Elapsed = Elapsed;
					S.Frames = *Frames;
					S.AvgFps = Elapsed > 0.0f ? *Frames / Elapsed : 0.0f;
					S.bFinished = Elapsed >= Duration;
					SetStats(S);
					if (S.bFinished)
					{
						SetRunning(false); // effect cleanup cancels the loop
						return;
					}
					SetRenderTick(++(*Tick)); // one coalesced re-render per frame
					Host->RequestFrame(*Loop);
				};
				Host->RequestFrame(*Loop);
				return [Cancelled]() { *Cancelled = true; };
			},
			Ruitk::Deps(bRunning, Version));
	
		const RuitkDemo::FStressStats S = Stats;
		FString Status;
		if (S.bFinished)
		{
			Status = FString::Printf(TEXT("DONE -- %d boxes | Avg FPS: %.1f | Duration: %.1fs | Frames: %d"),
										Boxes->Current.Num(), S.AvgFps, S.Elapsed, S.Frames);
		}
		else if (bRunning)
		{
			Status = FString::Printf(TEXT("Stress -- %d boxes | Avg FPS: %.1f | %.1fs | Frames: %d"), Boxes->Current.Num(),
										S.AvgFps, S.Elapsed, S.Frames);
		}
		else
		{
			Status = TEXT("Stress Test -- Ready (open `stat Ruitk` to watch the reconciler)");
		}
	
		auto StartRun = [bRunning, SetRunning, SetVersion, Version]() {
			if (!bRunning)
			{
				SetVersion(Version + 1);
				SetRunning(true);
			}
		};
#line 143 "StressTest.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((FText::FromString(Status)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(12.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(1.0f, 0.85f, 0.5f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.StressTest", "StressTest_1", "Duration(s): "), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkEditableTextBoxProps P;
		P.SetText((FText::FromString(DurationText)));
		P.SetOnTextChanged(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetDurationText(Value.TextValue.ToString()); }));
		return Ruitk::Slate::EditableTextBox(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.StressTest", "StressTest_2", "  Boxes: "), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkEditableTextBoxProps P;
		P.SetText((FText::FromString(CountText)));
		P.SetOnTextChanged(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetCountText(Value.TextValue.ToString()); }));
		return Ruitk::Slate::EditableTextBox(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { StartRun(); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("8,0,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((FText::FromString(bRunning ? TEXT("Running...") : (S.bFinished ? TEXT("Restart") : TEXT("Start")))), FRuitkKey()));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((RuitkDemo::StressAreaW));
		P.SetHeightOverride((RuitkDemo::StressAreaH));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkOverlayProps P;
		TArray<FRuitkNode> Ch;
		for (const RuitkDemo::FStressBox& StressBox : Boxes->Current)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((StressBox.Size));
		P.SetHeightOverride((StressBox.Size));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("RenderTranslation")), FRuitkValue(StressBox.Pos));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("left")));
		__Slot->Add(FName(TEXT("Slot.VAlign")), FRuitkValue(TEXT("top")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((StressBox.Color));
		TArray<FRuitkNode> Ch;
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey(StressBox.Id));
	}());
		}
		return Ruitk::Slate::Overlay(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray StressTest_UetkxImpl(FRuitkContext& Ctx, const FStressTestUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return StressTest_UetkxBody_59AC27E6(Ctx, Props, children);
}
static const FName GStressTestUetkxId = Ruitk::RegisterComponentId((void*)&StressTest_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_StressTest_StressTest::StressTest")));
static constexpr uint32 StressTest_RUITK_HOOK_SIG = 0x00ED6E73u;
inline FRuitkNode StressTest(FStressTestUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&StressTest_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GStressTestUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_StressTest_StressTest::StressTest")), []() { return StressTest(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_StressTest_StressTest
#endif
