// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: DoomGame.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_DoomGame
{
struct FDoomGameUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FDoomGameUetkxProps& O = static_cast<const FDoomGameUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode DoomGame(FDoomGameUetkxProps InProps = FDoomGameUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_DoomGame
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_DoomGame
{
static FRuitkNodeArray DoomGame_UetkxBody_8E8CD597(FRuitkContext& Ctx, const FDoomGameUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 8 "Source/RuitkDemo/Screens/DoomDemo/DoomGame.uetkx"
	auto [bInGame, SetInGame] = Ctx.UseState<bool>(false);
		auto [Level, SetLevel] = Ctx.UseState<int32>(1);
		auto [Diff, SetDiff] = Ctx.UseState<int32>(1);
		auto [PlayCount, SetPlayCount] = Ctx.UseState<int32>(0);
	
		FRuitkCallback OnLevelChange = Ctx.UseStableAction([SetLevel](const FRuitkValue& Value) { SetLevel(static_cast<int32>(Value.IntValue)); });
		FRuitkCallback OnDiffChange = Ctx.UseStableAction([SetDiff](const FRuitkValue& Value) { SetDiff(static_cast<int32>(Value.IntValue)); });
		FRuitkCallback OnStart = Ctx.UseStableAction([SetInGame, SetPlayCount](const FRuitkValue&) {
			SetPlayCount([](const int32& N) { return N + 1; });
			SetInGame(true);
		});
	
		FRuitkCallback OnBackToMenu = Ctx.UseStableAction([SetInGame](const FRuitkValue&) { SetInGame(false); });
#line 41 "DoomGame.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBoxProps P;
		TArray<FRuitkNode> Ch;
		if (bInGame)
		{
			Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_DoomGameScreen::FDoomGameScreenUetkxProps P;
		P.Level = Level;
		P.Diff = Diff;
		P.OnBackToMenu = OnBackToMenu;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_DoomGameScreen::DoomGameScreen(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(*FString::Printf(TEXT("play%d"), PlayCount))));
	}());
		}
		else
		{
			Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMainMenu_DoomMainMenu::FDoomMainMenuUetkxProps P;
		P.Level = Level;
		P.Diff = Diff;
		P.OnLevelChange = OnLevelChange;
		P.OnDifficultyChange = OnDiffChange;
		P.OnStart = OnStart;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMainMenu_DoomMainMenu::DoomMainMenu(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(TEXT("menu"))));
	}());
		}
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray DoomGame_UetkxImpl(FRuitkContext& Ctx, const FDoomGameUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return DoomGame_UetkxBody_8E8CD597(Ctx, Props, children);
}
static const FName GDoomGameUetkxId = Ruitk::RegisterComponentId((void*)&DoomGame_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_DoomGame::DoomGame")));
static constexpr uint32 DoomGame_RUITK_HOOK_SIG = 0x7810B479u;
inline FRuitkNode DoomGame(FDoomGameUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&DoomGame_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GDoomGameUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_DoomGame::DoomGame")), []() { return DoomGame(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_DoomGame
#endif
