// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: DoomGameScreen.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "Doom/DoomGameHook.h"
#include "Doom/DoomMaps.h"
#include "Doom/DoomTypes.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_DoomDemo_DoomGameScreen
{
struct FDoomGameScreenUetkxProps final : public FRuitkPropsBase
{
	int32 Level = 1;
	int32 Diff = 1;
	FRuitkCallback OnBackToMenu = FRuitkCallback();

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FDoomGameScreenUetkxProps& O = static_cast<const FDoomGameScreenUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (Level == O.Level);
		bEq = bEq && (Diff == O.Diff);
		bEq = bEq && (OnBackToMenu == O.OnBackToMenu);
		return bEq;
	}
};
inline FRuitkNode DoomGameScreen(FDoomGameScreenUetkxProps InProps = FDoomGameScreenUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_DoomDemo_DoomGameScreen
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_DoomDemo_DoomGameScreen
{
static FRuitkNodeArray DoomGameScreen_UetkxBody_BDBFD227(FRuitkContext& Ctx, const FDoomGameScreenUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	const auto& Level = Props.Level;
	const auto& Diff = Props.Diff;
	const auto& OnBackToMenu = Props.OnBackToMenu;
#line 15 "Source/RuitkDemo/Screens/DoomDemo/DoomGameScreen.uetkx"
	// Local level state so LEVEL COMPLETE → "Next level" can advance without the menu; the
		// shell remounts this screen per START (keyed), so the prop seed is always fresh.
		auto [ActiveLevel, SetActiveLevel] = Ctx.UseState<int32>(Level);
		auto [RestartVersion, SetRestartVersion] = Ctx.UseState<int32>(0);
	
		auto View = RuitkDoom::UseDoomGame(Ctx, ActiveLevel, Diff, RestartVersion);
		const RuitkDoom::FGameState* St = View.State;
		const RuitkDoom::FDoomFrameGeometry* G = View.Geometry;
	
		const float ViewportW = static_cast<float>(RuitkDoom::C::VIEWPORT_W);
		const float ViewportH = static_cast<float>(RuitkDoom::C::VIEWPORT_H);
		const float HudH = static_cast<float>(RuitkDoom::C::HUD_HEIGHT);
	
		// ScaleToFit letterboxes the fixed-res game into WHATEVER the demo area gives us — the
		// siblings' windows ARE 800×590, so scaled-to-fit is the same feel. VAlign=bottom pins
		// the HUD to the window's bottom edge whenever width is the constraining axis.
#line 56 "DoomGameScreen.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkScaleBoxProps P;
		P.SetStretch(FName(TEXT("scaleToFit")));
		P.SetHAlign(FName(TEXT("center")));
		P.SetVAlign(FName(TEXT("bottom")));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((ViewportW));
		P.SetHeightOverride((ViewportH + HudH));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkOverlayProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((ViewportW));
		P.SetHeightOverride((ViewportH));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Clipping")), FRuitkValue(TEXT("clipToBounds")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkCanvasPanelProps P;
		TArray<FRuitkNode> Ch;
		for (const RuitkDoom::FDoomQuad& Q : G->Sky)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		for (const RuitkDoom::FDoomQuad& Q : G->FloorBackstop)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		for (const RuitkDoom::FDoomQuad& Q : G->CeilingBands)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		for (const RuitkDoom::FDoomQuad& Q : G->FloorBands)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		for (const RuitkDoom::FDoomQuad& Q : G->FloorRims)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		for (const RuitkDoom::FDoomQuad& Q : G->ExtraSegs)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		for (const RuitkDoom::FDoomQuad& Q : G->RiserRims)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		for (const RuitkDoom::FDoomQuad& Q : G->Walls)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		for (const RuitkDoom::FDoomQuad& Q : G->Sprites)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		for (const RuitkDoom::FDoomQuad& Q : G->Tracers)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Style->Add(FName(TEXT("RenderTransformAngle")), FRuitkValue(Q.Angle));
		__Style->Add(FName(TEXT("RenderTransformPivot")), FRuitkValue(FVector2D(0.0f, 0.5f)));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		for (const RuitkDoom::FDoomQuad& Q : G->Overlay)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((Q.Brush));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(Q.Tint));
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(Q.Position));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(Q.Size));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey(Q.Key));
	}());
		}
		return Ruitk::Slate::Canvas(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("right")));
		__Slot->Add(FName(TEXT("Slot.VAlign")), FRuitkValue(TEXT("top")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,8,8,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuiDemo_Screens_DoomDemo_components_DoomMinimap_DoomMinimap::FDoomMinimapUetkxProps P;
		P.State = St;
		P.Version = View.Version;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuiDemo_Screens_DoomDemo_components_DoomMinimap_DoomMinimap::DoomMinimap(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		if (View.bShowFps)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("left")));
		__Slot->Add(FName(TEXT("Slot.VAlign")), FRuitkValue(TEXT("top")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("8,8,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("FPS {}"), FMath::RoundToInt(View.Fps))), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(1.0f, 0.95f, 0.4f, 1.0f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(TEXT("fps"))));
	}());
		}
		if (St->Player.MessageTimer > 0.0f)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBoxProps P;
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.VAlign")), FRuitkValue(TEXT("top")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((FText::FromString(St->Player.MessageText)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(14.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.95f, 0.85f, 0.50f, 1.0f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(TEXT("msg"))));
	}());
		}
		if (!St->Player.Alive && !St->Victory)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.10f, 0.0f, 0.0f, 0.55f)));
		P.SetHAlign(FName(TEXT("center")));
		P.SetVAlign(FName(TEXT("center")));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("fill")));
		__Slot->Add(FName(TEXT("Slot.VAlign")), FRuitkValue(TEXT("fill")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomGameScreen", "DoomGameScreen_1", "YOU DIED"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(48.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.95f, 0.15f, 0.10f, 1.0f)));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 14.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetRestartVersion(RestartVersion + 1); }));
		P.SetContentPadding(FMargin(16,6));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,8,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomGameScreen", "DoomGameScreen_2", "Restart level"), FRuitkKey()));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { OnBackToMenu.Execute(); }));
		P.SetContentPadding(FMargin(16,6));
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomGameScreen", "DoomGameScreen_3", "Main menu"), FRuitkKey()));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(TEXT("died"))));
	}());
		}
		if (St->Victory)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.0f, 0.06f, 0.0f, 0.55f)));
		P.SetHAlign(FName(TEXT("center")));
		P.SetVAlign(FName(TEXT("center")));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("fill")));
		__Slot->Add(FName(TEXT("Slot.VAlign")), FRuitkValue(TEXT("fill")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomGameScreen", "DoomGameScreen_4", "LEVEL COMPLETE"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(42.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.60f, 0.95f, 0.40f, 1.0f)));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("Kills {} / {}   ·   Score {}"), St->KillCount, St->KillTotal, St->Score)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.85f, 0.85f, 0.70f, 1.0f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 14.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		if (ActiveLevel < RuitkDoom::LEVEL_COUNT)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetActiveLevel(ActiveLevel + 1); }));
		P.SetContentPadding(FMargin(16,6));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,8,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomGameScreen", "DoomGameScreen_5", "Next level"), FRuitkKey()));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(TEXT("next"))));
	}());
		}
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { OnBackToMenu.Execute(); }));
		P.SetContentPadding(FMargin(16,6));
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomGameScreen", "DoomGameScreen_6", "Main menu"), FRuitkKey()));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(TEXT("won"))));
	}());
		}
		return Ruitk::Slate::Overlay(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuiDemo_Screens_DoomDemo_components_DoomHUD_DoomHUD::FDoomHUDUetkxProps P;
		P.Health = St->Player.Health;
		P.Armor = St->Player.Armor;
		P.ArmorClass = St->Player.ArmorClass;
		P.Weapon = St->Player.Weapon;
		P.Ammo = St->Player.Ammo;
		P.OwnedWeapons = St->Player.OwnedWeapons;
		P.Keys = St->Player.Keys;
		P.Score = St->Score;
		P.KillCount = St->KillCount;
		P.KillTotal = St->KillTotal;
		P.MapName = RuitkDoom::LevelName(ActiveLevel);
		P.FaceState = St->Player.FaceState;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuiDemo_Screens_DoomDemo_components_DoomHUD_DoomHUD::DoomHUD(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::ScaleBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray DoomGameScreen_UetkxImpl(FRuitkContext& Ctx, const FDoomGameScreenUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return DoomGameScreen_UetkxBody_BDBFD227(Ctx, Props, children);
}
static const FName GDoomGameScreenUetkxId = Ruitk::RegisterComponentId((void*)&DoomGameScreen_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_DoomDemo_DoomGameScreen::DoomGameScreen")));
static constexpr uint32 DoomGameScreen_RUITK_HOOK_SIG = 0x72A626EBu;
inline FRuitkNode DoomGameScreen(FDoomGameScreenUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&DoomGameScreen_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GDoomGameScreenUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_DoomDemo_DoomGameScreen::DoomGameScreen")), []() { return DoomGameScreen(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_DoomDemo_DoomGameScreen
#endif
