// AUTO-GENERATED by RUICompile — DO NOT EDIT. Source: HostImportProof.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "Misc/DateTime.h"

#if defined(RUI_UETKX_DECL_PHASE)
namespace RuiUetkx_Source_RuiHostTests_GrammarProof_HostImportProof
{
struct FHostImportProofUetkxProps final : public FRuiPropsBase
{

	virtual bool Equals(const FRuiPropsBase& OtherBase) const override
	{
		const FHostImportProofUetkxProps& O = static_cast<const FHostImportProofUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuiNode HostImportProof(FHostImportProofUetkxProps InProps = FHostImportProofUetkxProps(), TArray<FRuiNode> InChildren = TArray<FRuiNode>(), FRuiKey InKey = FRuiKey());

} // namespace RuiUetkx_Source_RuiHostTests_GrammarProof_HostImportProof
#else
namespace RuiUetkx_Source_RuiHostTests_GrammarProof_HostImportProof
{
static FRuiNodeArray HostImportProof_UetkxImpl_9F33ABBB(FRuiContext& Ctx, const FHostImportProofUetkxProps& Props, const TArray<FRuiNode>& children)
{
#line 4 "Source/RuiHostTests/GrammarProof/HostImportProof.uetkx"
	// FDateTime lives in Misc/DateTime.h — NOT on the auto-included prelude list
		// (INCLUDE_RETIREMENT_PLAN.md §A); reaching it here proves the `import "@Header.h"`
		// host include (§B) actually emits the #include the setup code needs.
		const FDateTime Stamp = FDateTime(2026, 1, 1);
		const FString Label = FString::Printf(TEXT("year=%d"), Stamp.GetYear());
#line 34 "HostImportProof.uetkx.inl"
	return { RUI::TextBlock((FString(Label)), FRuiKey()) };
}
static const FName GHostImportProofUetkxId = RUI::RegisterComponentId((void*)&HostImportProof_UetkxImpl_9F33ABBB, FName(TEXT("RuiUetkx_Source_RuiHostTests_GrammarProof_HostImportProof::HostImportProof")));
static constexpr uint32 HostImportProof_RUI_HOOK_SIG = 0x811C9DC5u;
inline FRuiNode HostImportProof(FHostImportProofUetkxProps InProps, TArray<FRuiNode> InChildren, FRuiKey InKey)
{
	return RUI::FC(&HostImportProof_UetkxImpl_9F33ABBB, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GHostImportProofUetkxFactoryReg = RUI::RegisterNamedFactory(FName(TEXT("RuiUetkx_Source_RuiHostTests_GrammarProof_HostImportProof::HostImportProof")), []() { return HostImportProof(); });

} // namespace RuiUetkx_Source_RuiHostTests_GrammarProof_HostImportProof
#endif
