// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: AcceptanceLab.hooks.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_AcceptanceLab_hooks
{
inline TTuple<int32, TFunction<void()>, TFunction<void()>> UseLabState(FRuitkContext& Ctx, int32 Start);

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_AcceptanceLab_hooks
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_AcceptanceLab_hooks
{
static TTuple<int32, TFunction<void()>, TFunction<void()>> UseLabState_RuitkBody_9A978405(FRuitkContext& Ctx, int32 Start)
{
#line 19 "Source/RuitkDemo/Screens/AcceptanceLab/AcceptanceLab.hooks.uetkx"
	auto [Count, SetCount] = Ctx.UseState<int32>(Start);
		const int32 Current = Count;
		TFunction<void()> Increment = [SetCount, Current]() { SetCount(Current + 1); };
		TFunction<void()> Reset = [SetCount]() { SetCount(0); };
		return MakeTuple(Count, Increment, Reset);
#line 23 "AcceptanceLab.hooks.uetkx.inl"
}
inline TTuple<int32, TFunction<void()>, TFunction<void()>> UseLabState(FRuitkContext& Ctx, int32 Start)
{
	return UseLabState_RuitkBody_9A978405(Ctx, Start);
}

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_AcceptanceLab_AcceptanceLab_hooks
#endif
