// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: AcceptanceLab.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab
{
struct FAcceptanceLabUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FAcceptanceLabUetkxProps& O = static_cast<const FAcceptanceLabUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode AcceptanceLab(FAcceptanceLabUetkxProps InProps = FAcceptanceLabUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab
{
static FRuitkNodeArray AcceptanceLab_UetkxBody_24CDEE20(FRuitkContext& Ctx, const FAcceptanceLabUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 21 "Source/RuitkDemo/Screens/AcceptanceLab/AcceptanceLab.uetkx"
	// ── state (checklist B — HMR keeps these VALUES across style/structure saves) ──────────────
		// Imported hook: destructured from a 3-tuple. F12 on UseLabState jumps to AcceptanceLab.hooks.
		auto [Count, Increment, Reset] = RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_hooks::UseLabState(Ctx, 0);
	
		auto [Name, SetName] = Ctx.UseState<FString>(FString());
		auto [bChecked, SetChecked] = Ctx.UseState<bool>(true);
		auto [Ratio, SetRatio] = Ctx.UseState<float>(0.5f);
		auto [Tab, SetTab] = Ctx.UseState<int32>(0);
	
		// UseEffect (checklist A "Use Effect"): runs once on mount, flips a flag we display below.
		auto [bMounted, SetMounted] = Ctx.UseState<bool>(false);
		Ctx.UseEffect([SetMounted]() { SetMounted(true); }, Ruitk::Deps());
	
		// Ref={ } capture (section 9): the handle arrives on attach (post-commit); the effect flips
		// a flag so the label below proves the markup-level Ref actually fired.
		const TSharedRef<TRuitkRef<FRuitkHostHandle>>& RefTarget = Ctx.UseRef<FRuitkHostHandle>();
		auto [bRefAttached, SetRefAttached] = Ctx.UseState<bool>(false);
		Ctx.UseEffect(
			[RefTarget, SetRefAttached, bRefAttached]() {
				if (!bRefAttached && RefTarget->Current.IsValid()) { SetRefAttached(true); }
			},
			Ruitk::EveryCommit());
	
		// A fixed list for the @for section (keyed rows).
		static const TCHAR* Fruits[] = {TEXT("Apple"), TEXT("Banana"), TEXT("Cherry"), TEXT("Date")};
	
		// A mutable counter the bounded @while advances. It is re-declared (=0) every render, so the
		// loop always terminates at 3 — a SAFE, actually-iterating @while (not the @while(false) guard).
		int32 WhileI = 0;
	
		// ── 10 · MARKUP AS A VALUE (§4 markup-everywhere) — markup is first-class at every
		// expression boundary: assigned to a local (both the parenthesized and bare `=` spellings),
		// then spliced below with { Badge } / { Chip }. The same FRuitkNode splices TWICE — two
		// mounted instances from one value. Editing THIS markup and saving must HMR without
		// resetting the counter above (the hook signature ignores markup text).
		auto Badge = ([&]() -> FRuitkNode {
			FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("count is {}"), Count)), FRuitkKey());
			TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
			TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
			TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
			__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Accent()));
			if (!__Style->IsEmpty()) { __P->Style = __Style; }
			if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
			__N.Props = __P;
			return __N;
		}());
		FRuitkNode Chip = Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_1", "   a bare `=` markup value"), FRuitkKey());
#line 75 "AcceptanceLab.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Panel()));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkScrollBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_2", "Acceptance Lab — one screen to test them all"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(18.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Accent()));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("UseEffect mounted: {}"), bMounted)), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 8.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.04f, 0.04f, 0.06f, 0.9f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("1. Counter (hook): {}"), Count)), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { Increment(); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_3", "+1")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { Reset(); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_4", "Reset")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.04f, 0.04f, 0.06f, 0.9f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkEditableTextBoxProps P;
		P.SetText((FText::FromString(Name)));
		P.SetHintText(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_5", "Type here — the mirror below tracks you"));
		P.SetOnTextChanged(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetName(Value.TextValue.ToString()); }));
		return Ruitk::Slate::EditableTextBox(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("2. You typed: {}"), Name)), FRuitkKey()));
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.04f, 0.04f, 0.06f, 0.9f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkCheckBoxProps P;
		P.SetbIsChecked((bChecked));
		P.SetOnCheckStateChanged(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetChecked(Value.BoolValue); }));
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_6", "3. dim the label when checked"), FRuitkKey()));
		return Ruitk::Slate::CheckBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSliderProps P;
		P.SetValue((Ratio));
		P.SetMinValue((0.0f));
		P.SetMaxValue((1.0f));
		P.SetStepSize((0.01f));
		P.SetOnValueChanged(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetRatio(static_cast<float>(Value.FloatValue)); }));
		return Ruitk::Slate::Slider(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkProgressBarProps P;
		P.SetPercent((Ratio));
		return Ruitk::Slate::ProgressBar(MoveTemp(P), FRuitkKey());
	}());
		if (bChecked)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((FText::FromString(FString::Printf(TEXT("slider = %.2f (dimmed)"), Ratio))), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__P->Classes.Add(FName(TEXT("rui-demo-dim")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		}
		else
		{
			Ch.Add(Ruitk::TextBlock((FText::FromString(FString::Printf(TEXT("slider = %.2f"), Ratio))), FRuitkKey()));
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.04f, 0.04f, 0.06f, 0.9f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_7", "4. @if / @elif / @else (drag the slider above)"), FRuitkKey()));
		if (Ratio < 0.33f)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_8", "   LOW"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Warn()));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		}
		else if (Ratio < 0.66f)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_9", "   MID"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Accent()));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		}
		else
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_10", "   HIGH"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Good()));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.04f, 0.04f, 0.06f, 0.9f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_11", "5. @for over a keyed list"), FRuitkKey()));
		for (int32 i = 0; i < UE_ARRAY_COUNT(Fruits); ++i)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("   {}. {}"), i, Fruits[i])), FRuitkKey()));
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(Fruits[i])));
	}());
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.04f, 0.04f, 0.06f, 0.9f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_12", "6. @while (bounded, 3 rows)"), FRuitkKey()));
		while (WhileI < 3)
		{
			const int32 Shown = WhileI;
								++WhileI;
			Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("   while row {}"), Shown)), FRuitkKey(FName(*FString::Printf(TEXT("w%d"), Shown)))));
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.04f, 0.04f, 0.06f, 0.9f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetTab(0); }));
		P.SetContentPadding(FMargin(10,3));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_13", "Overview")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetTab(1); }));
		P.SetContentPadding(FMargin(10,3));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_14", "Details")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetTab(2); }));
		P.SetContentPadding(FMargin(10,3));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_15", "Other")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		switch (Tab)
		{
		case 0:
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_16", "7. @match → Overview tab"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Accent()));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
			break;
		}
		case 1:
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_17", "7. @match → Details tab"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Good()));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
			break;
		}
		default:
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_18", "7. @match → default (Other)"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Warn()));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
			break;
		}
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.04f, 0.04f, 0.06f, 0.9f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_19", "8. Imported sub-components (LabCard)"), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard::FLabCardUetkxProps P;
		P.Label = TEXT("Live count");
		P.Count = Count;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard::LabCard(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard::FLabCardUetkxProps P;
		P.Label = TEXT("Always zero");
		P.Count = 0;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard::LabCard(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof::FLabScopeProofUetkxProps P;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabScopeProof_LabScopeProof::LabScopeProof(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.04f, 0.04f, 0.06f, 0.9f)));
		P.Ref = ([RefTarget](const FRuitkHostHandle& H) { RefTarget->Current = H; });
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("9. Ref captured this Border - attached: {}"), bRefAttached)), FRuitkKey()));
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.04f, 0.04f, 0.06f, 0.9f)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_20", "10. Markup as a value (FRuitkNode locals, spliced below)"), FRuitkKey()));
		Ch.Add((Badge));
		Ch.Add((Badge));
		Ch.Add((Chip));
		Ch.Add((bChecked  ? Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_21", "   short-circuit chip (uncheck 3 to hide me)"), FRuitkKey()) : FRuitkNode()));
		Ch.Add((bMounted
								? [&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_22", "   ternary: mounted"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Good()));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}()
								: Ruitk::TextBlock(NSLOCTEXT("Uetkx.AcceptanceLab", "AcceptanceLab_23", "   ternary: not yet"), FRuitkKey())));
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::ScrollBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray AcceptanceLab_UetkxImpl(FRuitkContext& Ctx, const FAcceptanceLabUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return AcceptanceLab_UetkxBody_24CDEE20(Ctx, Props, children);
}
static const FName GAcceptanceLabUetkxId = Ruitk::RegisterComponentId((void*)&AcceptanceLab_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab::AcceptanceLab")));
static constexpr uint32 AcceptanceLab_RUITK_HOOK_SIG = 0x49531E04u;
inline FRuitkNode AcceptanceLab(FAcceptanceLabUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&AcceptanceLab_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GAcceptanceLabUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab::AcceptanceLab")), []() { return AcceptanceLab(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab
#endif
