// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: RouterDemo.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_RouterDemo_RouterDemo
{
struct FRouterDemoUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FRouterDemoUetkxProps& O = static_cast<const FRouterDemoUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode RouterDemo(FRouterDemoUetkxProps InProps = FRouterDemoUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_RouterDemo_RouterDemo
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_RouterDemo_RouterDemo
{
static FRuitkNodeArray RouterDemo_UetkxBody_2AE4B677(FRuitkContext& Ctx, const FRouterDemoUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 8 "Source/RuitkDemo/Screens/RouterDemo/RouterDemo.uetkx"
	TArray<Ruitk::FRuitkRoute> RouteList;
		RouteList.Add(Ruitk::FRuitkRoute{ TEXT("/"), RuitkUetkx_Source_RuiDemo_Screens_RouterDemo_components_RouterHome_RouterHome::RouterHome() });
		RouteList.Add(Ruitk::FRuitkRoute{ TEXT("/users/:id"), RuitkUetkx_Source_RuiDemo_Screens_RouterDemo_components_RouterUser_RouterUser::RouterUser() });
#line 31 "RouterDemo.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.RouterDemo", "RouterDemo_1", "Router — in-memory navigation"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(18.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.RouterDemo", "RouterDemo_2", "Two routes; :id is a dynamic segment read via UseParams."), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 8.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add((Ruitk::Router({ Ruitk::Routes(MoveTemp(RouteList)) }, /*InitialPath*/ TEXT("/"))));
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray RouterDemo_UetkxImpl(FRuitkContext& Ctx, const FRouterDemoUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return RouterDemo_UetkxBody_2AE4B677(Ctx, Props, children);
}
static const FName GRouterDemoUetkxId = Ruitk::RegisterComponentId((void*)&RouterDemo_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_RouterDemo_RouterDemo::RouterDemo")));
static constexpr uint32 RouterDemo_RUI_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode RouterDemo(FRouterDemoUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&RouterDemo_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GRouterDemoUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_RouterDemo_RouterDemo::RouterDemo")), []() { return RouterDemo(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_RouterDemo_RouterDemo
#endif
