// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: MvvmDemo.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_MvvmDemo_MvvmDemo
{
struct FMvvmDemoUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FMvvmDemoUetkxProps& O = static_cast<const FMvvmDemoUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode MvvmDemo(FMvvmDemoUetkxProps InProps = FMvvmDemoUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_MvvmDemo_MvvmDemo
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_MvvmDemo_MvvmDemo
{
static FRuitkNodeArray MvvmDemo_UetkxBody_212F4A7E(FRuitkContext& Ctx, const FMvvmDemoUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 3 "Source/RuitkDemo/Screens/MvvmDemo/MvvmDemo.uetkx"
	// A viewmodel we own: created once (UseMemo, empty deps), GC-rooted by the strong ptr, released on unmount.
		const TStrongObjectPtr<URuitkSignalViewModel>& VmPtr = Ctx.UseMemo<TStrongObjectPtr<URuitkSignalViewModel>>(
			[]() { return TStrongObjectPtr<URuitkSignalViewModel>(NewObject<URuitkSignalViewModel>()); }, Ruitk::Deps());
		URuitkSignalViewModel* Vm = VmPtr.Get();
	
		// The bridge: UseField subscribes once and re-renders when the VM's `Int` field broadcasts.
		const int32 N = Ruitk::Umg::UseField<int32>(Ctx, Vm, FName(TEXT("Int")), 0);
#line 35 "MvvmDemo.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.MvvmDemo", "MvvmDemo_1", "MVVM / FieldNotify -- their data feeds us"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.MvvmDemo", "MvvmDemo_2", "A URuitkSignalViewModel is written by the button; UseField re-renders on the field broadcast. They own the value; we own the structure."), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 10.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("viewmodel.Int = {}"), N)), FRuitkKey()));
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { Vm->SetInt(N + 1); }));
		P.SetContentPadding(FMargin(12,4));
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.MvvmDemo", "MvvmDemo_3", "viewmodel.SetInt(+1)")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray MvvmDemo_UetkxImpl(FRuitkContext& Ctx, const FMvvmDemoUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return MvvmDemo_UetkxBody_212F4A7E(Ctx, Props, children);
}
static const FName GMvvmDemoUetkxId = Ruitk::RegisterComponentId((void*)&MvvmDemo_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_MvvmDemo_MvvmDemo::MvvmDemo")));
static constexpr uint32 MvvmDemo_RUI_HOOK_SIG = 0x1676516Fu;
inline FRuitkNode MvvmDemo(FMvvmDemoUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&MvvmDemo_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GMvvmDemoUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_MvvmDemo_MvvmDemo::MvvmDemo")), []() { return MvvmDemo(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_MvvmDemo_MvvmDemo
#endif
