// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: ActivationProbe.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuiDemo_Screens_CommonUiDemo_components_ActivationProbe_ActivationProbe
{
struct FActivationProbeUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FActivationProbeUetkxProps& O = static_cast<const FActivationProbeUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode ActivationProbe(FActivationProbeUetkxProps InProps = FActivationProbeUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuiDemo_Screens_CommonUiDemo_components_ActivationProbe_ActivationProbe
#else
namespace RuitkUetkx_Source_RuiDemo_Screens_CommonUiDemo_components_ActivationProbe_ActivationProbe
{
static FRuitkNodeArray ActivationProbe_UetkxBody_8B4CBBB7(FRuitkContext& Ctx, const FActivationProbeUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 4 "Source/RuitkDemo/Screens/CommonUiDemo/components/ActivationProbe/ActivationProbe.uetkx"
	const bool bActive = Ruitk::CommonUI::UseIsActive(Ctx);
		const ERuitkInputMethod Method = Ruitk::CommonUI::UseInputMethod(Ctx);
		const FString MethodStr = Method == ERuitkInputMethod::Gamepad ? TEXT("Gamepad")
										: Method == ERuitkInputMethod::Touch ? TEXT("Touch")
																		: TEXT("Mouse & Keyboard");
#line 33 "ActivationProbe.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("Screen is {}"), bActive ? TEXT("ACTIVE") : TEXT("INACTIVE"))), FRuitkKey()));
		Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("Input method: {}"), MethodStr)), FRuitkKey()));
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray ActivationProbe_UetkxImpl(FRuitkContext& Ctx, const FActivationProbeUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return ActivationProbe_UetkxBody_8B4CBBB7(Ctx, Props, children);
}
static const FName GActivationProbeUetkxId = Ruitk::RegisterComponentId((void*)&ActivationProbe_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_CommonUiDemo_components_ActivationProbe_ActivationProbe::ActivationProbe")));
static constexpr uint32 ActivationProbe_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode ActivationProbe(FActivationProbeUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&ActivationProbe_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GActivationProbeUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuiDemo_Screens_CommonUiDemo_components_ActivationProbe_ActivationProbe::ActivationProbe")), []() { return ActivationProbe(); });

} // namespace RuitkUetkx_Source_RuiDemo_Screens_CommonUiDemo_components_ActivationProbe_ActivationProbe
#endif
