// AUTO-GENERATED aggregator - DO NOT EDIT. Regenerated by RuitkCompile; the
// compiled source-file SET stays constant, only these contents change (D-19).
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "CoreMinimal.h"
#include "RuitkContext.h"
#include "RuitkCoreElements.h"
#include "RuitkSignal.h"
#include "RuitkSlateElements.h"
#include "RuitkStyle.h"
#include "RuitkRouter.h"
#if __has_include("RuitkAssetBrush.h")
#include "RuitkAssetBrush.h"
#endif
#if __has_include("RuitkFieldHooks.h")
#include "RuitkFieldHooks.h"
#endif
#if __has_include("RuitkUmgElement.h")
#include "RuitkUmgElement.h"
#endif
#if __has_include("RuitkSignalViewModel.h")
#include "RuitkSignalViewModel.h"
#endif
#if __has_include("RuitkHostWidget.h")
#include "RuitkHostWidget.h"
#endif
#if __has_include("RuitkWorldSubsystem.h")
#include "RuitkWorldSubsystem.h"
#endif
#if __has_include("RuitkActivation.h")
#include "RuitkActivation.h"
#endif
#if __has_include("RuitkActivatableScreen.h")
#include "RuitkActivatableScreen.h"
#endif
#if __has_include("RuitkMvvmViewModel.h")
#include "RuitkMvvmViewModel.h"
#endif
#if __has_include("UObject/StrongObjectPtr.h")
#include "UObject/StrongObjectPtr.h"
#endif
#if __has_include("Engine/World.h")
#include "Engine/World.h"
#endif

#define RUITK_UETKX_DECL_PHASE
#include "../Screens/AcceptanceLab/AcceptanceLab.hooks.uetkx.inl"
#include "../Screens/AcceptanceLab/AcceptanceLab.style.uetkx.inl"
#include "../Screens/AcceptanceLab/components/LabCard/LabCard.uetkx.inl"
#include "../Screens/AcceptanceLab/components/LabScopeProof/LabScopeBadge.uetkx.inl"
#include "../Screens/ClickCounter/ClickCounter.uetkx.inl"
#include "../Screens/CommonUiDemo/components/ActivationProbe/ActivationProbe.uetkx.inl"
#include "../Screens/ContextDemo/components/DemoContextPanel/DemoContextPanel.uetkx.inl"
#include "../Screens/ContextDemo/ContextDemo.style.uetkx.inl"
#include "../Screens/ContextDemo/ContextDemo.uetkx.inl"
#include "../Screens/CustomDraw/CustomDraw.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomFace/DoomFace.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomHUD/DoomHUD.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomMainMenu/DoomMainMenu.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomMinimap/DoomMinimap.uetkx.inl"
#include "../Screens/DoomDemo/DoomGameScreen.uetkx.inl"
#include "../Screens/HelloWorld/HelloWorld.uetkx.inl"
#include "../Screens/InteropShowcase/components/ShowcaseProbe/ShowcaseProbe.uetkx.inl"
#include "../Screens/InteropShowcase/InteropShowcase.uetkx.inl"
#include "../Screens/KeyedDiff/KeyedDiff.uetkx.inl"
#include "../Screens/MvvmDemo/MvvmDemo.uetkx.inl"
#include "../Screens/RouterDemo/components/RouterHome/RouterHome.uetkx.inl"
#include "../Screens/RouterDemo/components/RouterUser/RouterUser.uetkx.inl"
#include "../Screens/RouterDemo/RouterDemo.uetkx.inl"
#include "../Screens/SignalCounter/components/SignalPanel/SignalPanel.uetkx.inl"
#include "../Screens/SignalCounter/SignalCounter.uetkx.inl"
#include "../Screens/SimpleCounter/SimpleCounter.hooks.uetkx.inl"
#include "../Screens/SimpleCounter/SimpleCounter.style.uetkx.inl"
#include "../Screens/SimpleCounter/SimpleCounter.uetkx.inl"
#include "../Screens/SimpleTextField/SimpleTextField.uetkx.inl"
#include "../Screens/SimpleUseEffect/SimpleUseEffect.uetkx.inl"
#include "../Screens/StressTest/StressTest.uetkx.inl"
#include "../Screens/StyledPanels/StyledPanels.uetkx.inl"
#include "../Screens/TicTacToe/TicTacToe.uetkx.inl"
#include "../Screens/UmgHostDemo/components/UmgHostInner/UmgHostInner.uetkx.inl"
#include "../Screens/UmgHostDemo/UmgHostDemo.uetkx.inl"
#include "../Screens/AcceptanceLab/components/LabScopeProof/LabScopeProof.uetkx.inl"
#include "../Screens/CommonUiDemo/CommonUiDemo.uetkx.inl"
#include "../Screens/DoomDemo/DoomGame.uetkx.inl"
#include "../Screens/AcceptanceLab/AcceptanceLab.uetkx.inl"
#undef RUITK_UETKX_DECL_PHASE
#include "../Screens/AcceptanceLab/AcceptanceLab.hooks.uetkx.inl"
#include "../Screens/AcceptanceLab/AcceptanceLab.style.uetkx.inl"
#include "../Screens/AcceptanceLab/components/LabCard/LabCard.uetkx.inl"
#include "../Screens/AcceptanceLab/components/LabScopeProof/LabScopeBadge.uetkx.inl"
#include "../Screens/ClickCounter/ClickCounter.uetkx.inl"
#include "../Screens/CommonUiDemo/components/ActivationProbe/ActivationProbe.uetkx.inl"
#include "../Screens/ContextDemo/components/DemoContextPanel/DemoContextPanel.uetkx.inl"
#include "../Screens/ContextDemo/ContextDemo.style.uetkx.inl"
#include "../Screens/ContextDemo/ContextDemo.uetkx.inl"
#include "../Screens/CustomDraw/CustomDraw.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomFace/DoomFace.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomHUD/DoomHUD.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomMainMenu/DoomMainMenu.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomMinimap/DoomMinimap.uetkx.inl"
#include "../Screens/DoomDemo/DoomGameScreen.uetkx.inl"
#include "../Screens/HelloWorld/HelloWorld.uetkx.inl"
#include "../Screens/InteropShowcase/components/ShowcaseProbe/ShowcaseProbe.uetkx.inl"
#include "../Screens/InteropShowcase/InteropShowcase.uetkx.inl"
#include "../Screens/KeyedDiff/KeyedDiff.uetkx.inl"
#include "../Screens/MvvmDemo/MvvmDemo.uetkx.inl"
#include "../Screens/RouterDemo/components/RouterHome/RouterHome.uetkx.inl"
#include "../Screens/RouterDemo/components/RouterUser/RouterUser.uetkx.inl"
#include "../Screens/RouterDemo/RouterDemo.uetkx.inl"
#include "../Screens/SignalCounter/components/SignalPanel/SignalPanel.uetkx.inl"
#include "../Screens/SignalCounter/SignalCounter.uetkx.inl"
#include "../Screens/SimpleCounter/SimpleCounter.hooks.uetkx.inl"
#include "../Screens/SimpleCounter/SimpleCounter.style.uetkx.inl"
#include "../Screens/SimpleCounter/SimpleCounter.uetkx.inl"
#include "../Screens/SimpleTextField/SimpleTextField.uetkx.inl"
#include "../Screens/SimpleUseEffect/SimpleUseEffect.uetkx.inl"
#include "../Screens/StressTest/StressTest.uetkx.inl"
#include "../Screens/StyledPanels/StyledPanels.uetkx.inl"
#include "../Screens/TicTacToe/TicTacToe.uetkx.inl"
#include "../Screens/UmgHostDemo/components/UmgHostInner/UmgHostInner.uetkx.inl"
#include "../Screens/UmgHostDemo/UmgHostDemo.uetkx.inl"
#include "../Screens/AcceptanceLab/components/LabScopeProof/LabScopeProof.uetkx.inl"
#include "../Screens/CommonUiDemo/CommonUiDemo.uetkx.inl"
#include "../Screens/DoomDemo/DoomGame.uetkx.inl"
#include "../Screens/AcceptanceLab/AcceptanceLab.uetkx.inl"
