// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: StyledPanels.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_StyledPanels_StyledPanels
{
struct FStyledPanelsUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FStyledPanelsUetkxProps& O = static_cast<const FStyledPanelsUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode StyledPanels(FStyledPanelsUetkxProps InProps = FStyledPanelsUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_StyledPanels_StyledPanels
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_StyledPanels_StyledPanels
{
static FRuitkNodeArray StyledPanels_UetkxBody_017C6E5E(FRuitkContext& Ctx, const FStyledPanelsUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 2 "Source/RuitkDemo/Screens/StyledPanels/StyledPanels.uetkx"
	auto [bDim, SetDim] = Ctx.UseState<bool>(false);
		auto [Text, SetText] = Ctx.UseState<FString>(FString(TEXT("type here")));
#line 30 "StyledPanels.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.StyledPanels", "StyledPanels_1", "Styled panels"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.6f, 1.0f, 0.6f)));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkCheckBoxProps P;
		P.SetbIsChecked((bDim));
		P.SetOnCheckStateChanged(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetDim(Value.BoolValue); }));
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.StyledPanels", "StyledPanels_2", "dim the mirror"), FRuitkKey()));
		return Ruitk::Slate::CheckBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkEditableTextBoxProps P;
		P.SetText((FText::FromString(Text)));
		P.SetOnTextChanged(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetText(Value.TextValue.ToString()); }));
		return Ruitk::Slate::EditableTextBox(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		if (bDim)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock((Ruitk::Fmt(TEXT("mirror: {}"), Text)), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__P->Classes.Add(FName(TEXT("rui-demo-dim")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		}
		else
		{
			Ch.Add(Ruitk::TextBlock((Ruitk::Fmt(TEXT("mirror: {}"), Text)), FRuitkKey()));
		}
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray StyledPanels_UetkxImpl(FRuitkContext& Ctx, const FStyledPanelsUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return StyledPanels_UetkxBody_017C6E5E(Ctx, Props, children);
}
static const FName GStyledPanelsUetkxId = Ruitk::RegisterComponentId((void*)&StyledPanels_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_StyledPanels_StyledPanels::StyledPanels")));
static constexpr uint32 StyledPanels_RUITK_HOOK_SIG = 0x72A626EBu;
inline FRuitkNode StyledPanels(FStyledPanelsUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&StyledPanels_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GStyledPanelsUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_StyledPanels_StyledPanels::StyledPanels")), []() { return StyledPanels(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_StyledPanels_StyledPanels
#endif
