// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: DoomFace.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "Doom/DoomTextures.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomFace_DoomFace
{
struct FDoomFaceUetkxProps final : public FRuitkPropsBase
{
	int32 Frame = 0;

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FDoomFaceUetkxProps& O = static_cast<const FDoomFaceUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (Frame == O.Frame);
		return bEq;
	}
};
inline FRuitkNode DoomFace(FDoomFaceUetkxProps InProps = FDoomFaceUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomFace_DoomFace
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomFace_DoomFace
{
static FRuitkNodeArray DoomFace_UetkxBody_E0AA4BE4(FRuitkContext& Ctx, const FDoomFaceUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	const auto& Frame = Props.Frame;
#line 7 "Source/RuitkDemo/Screens/DoomDemo/components/DoomFace/DoomFace.uetkx"
	const int32 Idx = FMath::Clamp(Frame, 0, 7);
		const FLinearColor PanelBg(0.20f, 0.16f, 0.10f, 1.0f);
		const FLinearColor BorderClr(0.85f, 0.55f, 0.20f, 1.0f);
		const FLinearColor LabelClr(0.85f, 0.70f, 0.35f, 1.0f);
	
		// The face brush is cached per frame index: MakeAssetBrush GC-roots the transient
		// texture, and UseMemo keeps the brush IDENTITY stable across renders (FRuitkImageProps
		// compares the shared pointer) — re-created only when Idx changes.
		const TSharedPtr<FSlateBrush>& FaceBrush = Ctx.UseMemo<TSharedPtr<FSlateBrush>>(
			[Idx]() { return Ruitk::Umg::MakeAssetBrush(RuitkDoom::FDoomTextures::Face(Idx), FVector2D(48.0f, 48.0f)); },
			Ruitk::Deps(Idx));
	
		// The mug is 48px (not the siblings' 64): the bar's inner height is HUD_HEIGHT 90 minus
		// top border + bar/panel padding = ~65px, and label(13) + 48 is what actually FITS —
		// Slate neither shrinks nor clips overflow, so 64 spilled below the bar (playtest #2).
#line 47 "DoomFace.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((68.0f));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,0,4,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((BorderClr));
		P.SetPadding(FMargin(1));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((PanelBg));
		P.SetPadding(FMargin(0,1));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.DoomFace", "DoomFace_1", "DOOMGUY"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(10.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(LabelClr));
		__Style->Add(FName(TEXT("Justification")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,1")));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkImageProps P;
		P.SetImage((FaceBrush));
		P.SetDesiredSizeOverride((FVector2D(48.0f, 48.0f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.HAlign")), FRuitkValue(TEXT("center")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		return Ruitk::Slate::Image(MoveTemp(P), FRuitkKey());
	}());
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray DoomFace_UetkxImpl(FRuitkContext& Ctx, const FDoomFaceUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return DoomFace_UetkxBody_E0AA4BE4(Ctx, Props, children);
}
static const FName GDoomFaceUetkxId = Ruitk::RegisterComponentId((void*)&DoomFace_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomFace_DoomFace::DoomFace")));
static constexpr uint32 DoomFace_RUITK_HOOK_SIG = 0x1676516Fu;
inline FRuitkNode DoomFace(FDoomFaceUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&DoomFace_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GDoomFaceUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomFace_DoomFace::DoomFace")), []() { return DoomFace(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomFace_DoomFace
#endif
