// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: CommonUiDemo.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "RuitkDemoSupport.h"
#include "DemoInteropWidgets.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_CommonUiDemo_CommonUiDemo
{
struct FCommonUiDemoUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FCommonUiDemoUetkxProps& O = static_cast<const FCommonUiDemoUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode CommonUiDemo(FCommonUiDemoUetkxProps InProps = FCommonUiDemoUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_CommonUiDemo_CommonUiDemo
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_CommonUiDemo_CommonUiDemo
{
static FRuitkNodeArray CommonUiDemo_UetkxBody_12FB8942(FRuitkContext& Ctx, const FCommonUiDemoUetkxProps& Props, const TArray<FRuitkNode>& children)
{
#line 12 "Source/RuitkDemo/Screens/CommonUiDemo/CommonUiDemo.uetkx"
	auto [bActive, SetActive] = Ctx.UseState<bool>(true);
		UWorld* World = RuitkDemo::GetDemoWorld();
	
		FRuitkActivationState State;
		State.bActive = bActive;
		State.InputMethod = ERuitkInputMethod::MouseAndKeyboard;
		Ctx.ProvideContext(Ruitk::CommonUI::ActivationContext(), State);
#line 37 "CommonUiDemo.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkVerticalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.CommonUiDemo", "CommonUiDemo_1", "CommonUI -- activation feeds us"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(16.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 6.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.CommonUiDemo", "CommonUiDemo_2", "1. The hooks, driven by a toggle (works headless -- ProvideContext stands in):"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuitkNode {
		RuitkUetkx_Source_RuitkDemo_Screens_CommonUiDemo_components_ActivationProbe_ActivationProbe::FActivationProbeUetkxProps P;
		TArray<FRuitkNode> Ch;
		return RuitkUetkx_Source_RuitkDemo_Screens_CommonUiDemo_components_ActivationProbe_ActivationProbe::ActivationProbe(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkHorizontalBoxProps P;
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkButtonProps P;
		P.SetOnClicked(FRuitkCallback::Create([=](const FRuitkValue& Value) { SetActive(!bActive); }));
		P.SetContentPadding(FMargin(12,4));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,4,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.CommonUiDemo", "CommonUiDemo_3", "Toggle activation")));
		return Ruitk::Slate::Button(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::HorizontalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkSpacerProps P;
		P.SetSize((FVector2D(1.0f, 12.0f)));
		return Ruitk::Slate::Spacer(MoveTemp(P), FRuitkKey());
	}());
		Ch.Add([&]() -> FRuitkNode {
		FRuitkNode __N = Ruitk::TextBlock(NSLOCTEXT("Uetkx.CommonUiDemo", "CommonUiDemo_4", "2. THE REAL THING -- our screen pushed onto a real CommonUI activatable stack:"), FRuitkKey());
		TSharedRef<FRuitkTextBlockProps> __P = MakeShared<FRuitkTextBlockProps>(static_cast<const FRuitkTextBlockProps&>(*__N.Props));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuitkValue(FLinearColor(0.7f, 0.7f, 0.8f)));
		__Style->Add(FName(TEXT("Font.Size")), FRuitkValue(11.0f));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add((World ? Ruitk::Umg::UserWidget(UDemoStackHostWidget::StaticClass(), World) : Ruitk::TextBlock(FString(TEXT("[press Play -- the real stack needs a running world]")))));
		return Ruitk::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray CommonUiDemo_UetkxImpl(FRuitkContext& Ctx, const FCommonUiDemoUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return CommonUiDemo_UetkxBody_12FB8942(Ctx, Props, children);
}
static const FName GCommonUiDemoUetkxId = Ruitk::RegisterComponentId((void*)&CommonUiDemo_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_CommonUiDemo_CommonUiDemo::CommonUiDemo")));
static constexpr uint32 CommonUiDemo_RUITK_HOOK_SIG = 0xF574B6D3u;
inline FRuitkNode CommonUiDemo(FCommonUiDemoUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&CommonUiDemo_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GCommonUiDemoUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_CommonUiDemo_CommonUiDemo::CommonUiDemo")), []() { return CommonUiDemo(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_CommonUiDemo_CommonUiDemo
#endif
