// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: DoomMinimap.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "Doom/DoomTypes.h"

#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMinimap_DoomMinimap
{
struct FDoomMinimapUetkxProps final : public FRuitkPropsBase
{
	const RuitkDoom::FGameState* State = nullptr;
	int32 Version = 0;

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FDoomMinimapUetkxProps& O = static_cast<const FDoomMinimapUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (State == O.State);
		bEq = bEq && (Version == O.Version);
		return bEq;
	}
};
inline FRuitkNode DoomMinimap(FDoomMinimapUetkxProps InProps = FDoomMinimapUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMinimap_DoomMinimap
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMinimap_DoomMinimap
{
static FRuitkNodeArray DoomMinimap_UetkxBody_72C99BCC(FRuitkContext& Ctx, const FDoomMinimapUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	const auto& State = Props.State;
	const auto& Version = Props.Version;
#line 10 "Source/RuitkDemo/Screens/DoomDemo/components/DoomMinimap/DoomMinimap.uetkx"
	(void)Version; // re-render key only
	
		constexpr int32 MAP_PX = 160;
	
		const FLinearColor BgClr(0.05f, 0.05f, 0.05f, 0.78f);
		const FLinearColor BorderClr(0.85f, 0.55f, 0.20f, 1.0f);
		const FLinearColor WallClr(0.55f, 0.40f, 0.20f, 1.0f);
		const FLinearColor DoorClr(0.85f, 0.65f, 0.10f, 1.0f);
		const FLinearColor DoorBlueClr(0.30f, 0.55f, 1.00f, 1.0f);
		const FLinearColor DoorYellowClr(0.95f, 0.85f, 0.20f, 1.0f);
		const FLinearColor DoorRedClr(0.95f, 0.20f, 0.20f, 1.0f);
		const FLinearColor ExitClr(0.40f, 0.95f, 0.40f, 1.0f);
		const FLinearColor PlayerClr(0.95f, 0.95f, 0.50f, 1.0f);
		const FLinearColor EnemyClr(0.95f, 0.20f, 0.15f, 1.0f);
		const FLinearColor PickupClr(0.30f, 0.85f, 0.85f, 1.0f);
	
		const int32 Mw = State != nullptr ? State->Map.Width : 1;
		const int32 Mh = State != nullptr ? State->Map.Height : 1;
		const float Scale = static_cast<float>(MAP_PX) / static_cast<float>(FMath::Max(Mw, Mh));
		const int32 InnerW = FMath::RoundToInt(Mw * Scale);
		const int32 InnerH = FMath::RoundToInt(Mh * Scale);
		const int32 CellPx = FMath::Max(1, FMath::RoundToInt(Scale));
	
		struct FQuad
		{
			float X = 0.0f;
			float Y = 0.0f;
			FLinearColor Color = FLinearColor::White;
		};
	
		// Map cells (walls/doors/exits) — same color classification as the original.
		TArray<FQuad> Cells;
		if (State != nullptr)
		{
			Cells.Reserve(64);
			for (int32 Cy = 0; Cy < Mh; ++Cy)
			{
				for (int32 Cx = 0; Cx < Mw; ++Cx)
				{
					const RuitkDoom::FCell& Cell = State->Map.Cells[Cy * Mw + Cx];
					FLinearColor Col;
					if (Cell.Kind == RuitkDoom::ECellKind::Wall) { Col = WallClr; }
					else if (Cell.Kind == RuitkDoom::ECellKind::Exit) { Col = ExitClr; }
					else if (Cell.Kind == RuitkDoom::ECellKind::DoorBlue) { Col = DoorBlueClr; }
					else if (Cell.Kind == RuitkDoom::ECellKind::DoorYellow) { Col = DoorYellowClr; }
					else if (Cell.Kind == RuitkDoom::ECellKind::DoorRed) { Col = DoorRedClr; }
					else if (Cell.Kind == RuitkDoom::ECellKind::Door) { Col = DoorClr; }
					else { continue; }
					FQuad Q;
					Q.X = Cx * Scale;
					Q.Y = (Mh - 1 - Cy) * Scale;
					Q.Color = Col;
					Cells.Add(Q);
				}
			}
		}
	
		// Mobj dots: enemies red, keys their card color, pickups cyan (dead/collected skipped).
		TArray<FQuad> Dots;
		if (State != nullptr)
		{
			Dots.Reserve(State->Mobjs.Num());
			for (int32 i = 0; i < State->Mobjs.Num(); ++i)
			{
				const RuitkDoom::FMobj& M = State->Mobjs[i];
				if (M.Collected || M.State == RuitkDoom::EAIState::Dead)
				{
					continue;
				}
				FLinearColor Dc;
				switch (M.Kind)
				{
				case RuitkDoom::EMobjKind::Imp:
				case RuitkDoom::EMobjKind::Demon:
				case RuitkDoom::EMobjKind::Baron:
				case RuitkDoom::EMobjKind::Cacodemon:
				case RuitkDoom::EMobjKind::LostSoul:
				case RuitkDoom::EMobjKind::Zombieman:
				case RuitkDoom::EMobjKind::Shotgunner:
					Dc = EnemyClr;
					break;
				case RuitkDoom::EMobjKind::KeyBlue:
					Dc = DoorBlueClr;
					break;
				case RuitkDoom::EMobjKind::KeyYellow:
					Dc = DoorYellowClr;
					break;
				case RuitkDoom::EMobjKind::KeyRed:
					Dc = DoorRedClr;
					break;
				case RuitkDoom::EMobjKind::PickupHealth:
				case RuitkDoom::EMobjKind::PickupArmor:
				case RuitkDoom::EMobjKind::PickupArmorBlue:
				case RuitkDoom::EMobjKind::PickupBullets:
				case RuitkDoom::EMobjKind::PickupShells:
				case RuitkDoom::EMobjKind::PickupRockets:
				case RuitkDoom::EMobjKind::PickupCells:
				case RuitkDoom::EMobjKind::PickupShotgun:
				case RuitkDoom::EMobjKind::PickupChaingun:
				case RuitkDoom::EMobjKind::PickupRocketLauncher:
				case RuitkDoom::EMobjKind::PickupPlasma:
				case RuitkDoom::EMobjKind::PickupBFG:
					Dc = PickupClr;
					break;
				default:
					continue;
				}
				FQuad Q;
				Q.X = M.X * Scale;
				Q.Y = (Mh - M.Y) * Scale;
				Q.Color = Dc;
				Dots.Add(Q);
			}
		}
	
		const float PxX = State != nullptr ? State->Player.X * Scale : 0.0f;
		const float PxY = State != nullptr ? (Mh - State->Player.Y) * Scale : 0.0f;
		const float PAngle = State != nullptr ? State->Player.Angle : 0.0f;
#line 153 "DoomMinimap.uetkx.inl"
	return { [&]() -> FRuitkNode {
		FRuitkBoxProps P;
		P.SetWidthOverride((static_cast<float>(InnerW + 6)));
		P.SetHeightOverride((static_cast<float>(InnerH + 6)));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((BorderClr));
		P.SetPadding(FMargin(1));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((BgClr));
		P.SetPadding(FMargin(2));
		TArray<FRuitkNode> Ch;
		Ch.Add([&]() -> FRuitkNode {
		FRuitkCanvasPanelProps P;
		TArray<FRuitkNode> Ch;
		for (int32 i = 0; i < Cells.Num(); ++i)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((Cells[i].Color));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(FVector2D(Cells[i].X, Cells[i].Y)));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(FVector2D(static_cast<float>(CellPx), static_cast<float>(CellPx))));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(*FString::Printf(TEXT("c%d"), i))));
	}());
		}
		for (int32 i = 0; i < Dots.Num(); ++i)
		{
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((Dots[i].Color));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(FVector2D(Dots[i].X - 2.0f, Dots[i].Y - 2.0f)));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(FVector2D(4.0f, 4.0f)));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(*FString::Printf(TEXT("m%d"), i))));
	}());
		}
		if (State != nullptr)
		{
			// Player marker.
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((PlayerClr));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(FVector2D(PxX - 3.0f, PxY - 3.0f)));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(FVector2D(6.0f, 6.0f)));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(TEXT("player"))));
	}());
		}
		if (State != nullptr)
		{
			// Heading indicator.
			Ch.Add([&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((PlayerClr));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Position")), FRuitkValue(FVector2D(PxX + FMath::Cos(PAngle) * 4.0f - 1.0f, PxY - FMath::Sin(PAngle) * 4.0f - 1.0f)));
		__Slot->Add(FName(TEXT("Slot.Size")), FRuitkValue(FVector2D(2.0f, 2.0f)));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey(FName(TEXT("heading"))));
	}());
		}
		return Ruitk::Slate::Canvas(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}());
		return Ruitk::Slate::Box(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray DoomMinimap_UetkxImpl(FRuitkContext& Ctx, const FDoomMinimapUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return DoomMinimap_UetkxBody_72C99BCC(Ctx, Props, children);
}
static const FName GDoomMinimapUetkxId = Ruitk::RegisterComponentId((void*)&DoomMinimap_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMinimap_DoomMinimap::DoomMinimap")));
static constexpr uint32 DoomMinimap_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode DoomMinimap(FDoomMinimapUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&DoomMinimap_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GDoomMinimapUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMinimap_DoomMinimap::DoomMinimap")), []() { return DoomMinimap(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_DoomDemo_components_DoomMinimap_DoomMinimap
#endif
