// AUTO-GENERATED by RUICompile — DO NOT EDIT. Source: LabCard.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUI_UETKX_DECL_PHASE)
namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard
{
struct FLabCardUetkxProps final : public FRuiPropsBase
{
	FString Label = FString(TEXT("Card"));
	int32 Count = 0;

	virtual bool Equals(const FRuiPropsBase& OtherBase) const override
	{
		const FLabCardUetkxProps& O = static_cast<const FLabCardUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		bEq = bEq && (Label == O.Label);
		bEq = bEq && (Count == O.Count);
		return bEq;
	}
};
inline FRuiNode LabCard(FLabCardUetkxProps InProps = FLabCardUetkxProps(), TArray<FRuiNode> InChildren = TArray<FRuiNode>(), FRuiKey InKey = FRuiKey());

} // namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard
#else
namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard
{
static FRuiNodeArray LabCard_UetkxBody_0A2A00D8(FRuiContext& Ctx, const FLabCardUetkxProps& Props, const TArray<FRuiNode>& children)
{
	const auto& Label = Props.Label;
	const auto& Count = Props.Count;
#line 18 "Source/RuiDemo/Screens/AcceptanceLab/components/LabCard/LabCard.uetkx"
	// Simple derived value from a prop — exercises reading component props in the setup block.
		const FLinearColor Tint = Count > 0 ? RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Good() : RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Warn();
#line 36 "LabCard.uetkx.inl"
	return { [&]() -> FRuiNode {
		FRuiBorderProps P;
		P.SetPadding(FMargin(8));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.05f, 0.05f, 0.07f, 0.9f)));
		TSharedRef<FRuiStyleDict> __Style = MakeShared<FRuiStyleDict>();
		TSharedRef<FRuiStyleDict> __Slot = MakeShared<FRuiStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuiValue(TEXT("0,0,6,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuiNode> Ch;
		Ch.Add([&]() -> FRuiNode {
		FRuiVerticalBoxProps P;
		TArray<FRuiNode> Ch;
		Ch.Add([&]() -> FRuiNode {
		FRuiNode __N = RUI::TextBlock((FText::FromString(Label)), FRuiKey());
		TSharedRef<FRuiTextBlockProps> __P = MakeShared<FRuiTextBlockProps>(static_cast<const FRuiTextBlockProps&>(*__N.Props));
		TSharedRef<FRuiStyleDict> __Style = MakeShared<FRuiStyleDict>();
		TSharedRef<FRuiStyleDict> __Slot = MakeShared<FRuiStyleDict>();
		__Style->Add(FName(TEXT("Font.Size")), FRuiValue(12.0f));
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuiValue(RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_AcceptanceLab_style::Accent()));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		Ch.Add([&]() -> FRuiNode {
		FRuiNode __N = RUI::TextBlock((RUI::Fmt(TEXT("value = {}"), Count)), FRuiKey());
		TSharedRef<FRuiTextBlockProps> __P = MakeShared<FRuiTextBlockProps>(static_cast<const FRuiTextBlockProps&>(*__N.Props));
		TSharedRef<FRuiStyleDict> __Style = MakeShared<FRuiStyleDict>();
		TSharedRef<FRuiStyleDict> __Slot = MakeShared<FRuiStyleDict>();
		__Style->Add(FName(TEXT("ColorAndOpacity")), FRuiValue(Tint));
		if (!__Style->IsEmpty()) { __P->Style = __Style; }
		if (!__Slot->IsEmpty()) { __P->SlotProps = __Slot; }
		__N.Props = __P;
		return __N;
	}());
		return RUI::Slate::VerticalBox(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}());
		return RUI::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuiKey());
	}() };
}
static FRuiNodeArray LabCard_UetkxImpl(FRuiContext& Ctx, const FLabCardUetkxProps& Props, const TArray<FRuiNode>& children)
{
	return LabCard_UetkxBody_0A2A00D8(Ctx, Props, children);
}
static const FName GLabCardUetkxId = RUI::RegisterComponentId((void*)&LabCard_UetkxImpl, FName(TEXT("RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard::LabCard")));
static constexpr uint32 LabCard_RUI_HOOK_SIG = 0x811C9DC5u;
inline FRuiNode LabCard(FLabCardUetkxProps InProps, TArray<FRuiNode> InChildren, FRuiKey InKey)
{
	return RUI::FC(&LabCard_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GLabCardUetkxFactoryReg = RUI::RegisterNamedFactory(FName(TEXT("RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard::LabCard")), []() { return LabCard(); });

} // namespace RuiUetkx_Source_RuiDemo_Screens_AcceptanceLab_components_LabCard_LabCard
#endif
