// AUTO-GENERATED by RuitkCompile — DO NOT EDIT. Source: HelloWorld.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUITK_UETKX_DECL_PHASE)
namespace RuitkUetkx_Source_RuitkDemo_Screens_HelloWorld_HelloWorld
{
struct FHelloWorldUetkxProps final : public FRuitkPropsBase
{

	virtual bool Equals(const FRuitkPropsBase& OtherBase) const override
	{
		const FHelloWorldUetkxProps& O = static_cast<const FHelloWorldUetkxProps&>(OtherBase);
		bool bEq = BaseFieldsEqual(O);
		return bEq;
	}
};
inline FRuitkNode HelloWorld(FHelloWorldUetkxProps InProps = FHelloWorldUetkxProps(), TArray<FRuitkNode> InChildren = TArray<FRuitkNode>(), FRuitkKey InKey = FRuitkKey());

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_HelloWorld_HelloWorld
#else
namespace RuitkUetkx_Source_RuitkDemo_Screens_HelloWorld_HelloWorld
{
static FRuitkNodeArray HelloWorld_UetkxBody_6146BE1F(FRuitkContext& Ctx, const FHelloWorldUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return { [&]() -> FRuitkNode {
		FRuitkBorderProps P;
		P.SetPadding(FMargin(12));
		P.SetBorderImage(FName(TEXT("WhiteBrush")));
		P.SetBorderBackgroundColor((FLinearColor(0.02f, 0.02f, 0.03f, 0.85f)));
		TSharedRef<FRuitkStyleDict> __Style = MakeShared<FRuitkStyleDict>();
		TSharedRef<FRuitkStyleDict> __Slot = MakeShared<FRuitkStyleDict>();
		__Slot->Add(FName(TEXT("Slot.Padding")), FRuitkValue(TEXT("0,10,0,0")));
		if (!__Style->IsEmpty()) { P.Style = __Style; }
		if (!__Slot->IsEmpty()) { P.SlotProps = __Slot; }
		TArray<FRuitkNode> Ch;
		Ch.Add(Ruitk::TextBlock(NSLOCTEXT("Uetkx.HelloWorld", "HelloWorld_1", "Hello, world! (compiled from HelloWorld.uetkx)"), FRuitkKey()));
		return Ruitk::Slate::Border(MoveTemp(P), MoveTemp(Ch), FRuitkKey());
	}() };
}
static FRuitkNodeArray HelloWorld_UetkxImpl(FRuitkContext& Ctx, const FHelloWorldUetkxProps& Props, const TArray<FRuitkNode>& children)
{
	return HelloWorld_UetkxBody_6146BE1F(Ctx, Props, children);
}
static const FName GHelloWorldUetkxId = Ruitk::RegisterComponentId((void*)&HelloWorld_UetkxImpl, FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_HelloWorld_HelloWorld::HelloWorld")));
static constexpr uint32 HelloWorld_RUITK_HOOK_SIG = 0x811C9DC5u;
inline FRuitkNode HelloWorld(FHelloWorldUetkxProps InProps, TArray<FRuitkNode> InChildren, FRuitkKey InKey)
{
	return Ruitk::FC(&HelloWorld_UetkxImpl, MoveTemp(InProps), MoveTemp(InChildren), InKey);
}
static const bool GHelloWorldUetkxFactoryReg = Ruitk::RegisterNamedFactory(FName(TEXT("RuitkUetkx_Source_RuitkDemo_Screens_HelloWorld_HelloWorld::HelloWorld")), []() { return HelloWorld(); });

} // namespace RuitkUetkx_Source_RuitkDemo_Screens_HelloWorld_HelloWorld
#endif
